### ISSUE TITLE
Support for ECDHE_ECDSA broken?

### ISSUE THREAD

**Issue by boaks** [bcgit/bc-java#1053]
I currently try to use Bouncy Castle as JSSE for netty.io in [Eclipse/Californium](https://github.com/eclipse/californium).

I use netty.io 4.1.69.Final. I run it on Windows 10, using openjdk 11.

My bouncy castle dependencies are:

```
<properties>
	<bc.version>1.69</bc.version>
</properties>
<dependencies>
	<dependency>
		<groupId>org.bouncycastle</groupId>
		<artifactId>bcpkix-jdk15on</artifactId>
		<version>${bc.version}</version>
		<scope>test</scope>
	</dependency>
	<dependency>
		<groupId>org.bouncycastle</groupId>
		<artifactId>bcprov-jdk15on</artifactId>
		<version>${bc.version}</version>
		<scope>test</scope>
	</dependency>
	<dependency>
		<groupId>org.bouncycastle</groupId>
		<artifactId>bctls-jdk15on</artifactId>
		<version>${bc.version}</version>
		<scope>test</scope>
	</dependency>
</dependencies>
```

I add the org.bouncycastle.jce.provider.BouncyCastleProvider to Security at position 1, and org.bouncycastle.jsse.provider.BouncyCastleJsseProvider at position 2. 
I configure the BouncyCastleJsseProvider with "ssl.KeyManagerFactory.algorithm"="PKIX" and "ssl.TrustManagerFactory.algorithm"="PKIX".

I use a keystore with ECDSA certificates.

The handshake fails with the message

> org.bouncycastle.tls.TlsFatalAlert: handshake_failure(40); No selectable cipher suite
> 	at org.bouncycastle.tls.AbstractTlsServer.getSelectedCipherSuite(AbstractTlsServer.java:438)

(With Suns JSSE using the same keystore works.)

As far as I could debug the root cause,  it seems for me that, the SunX509KeyManagerImpl doesn't return credentials, when "ECDHE_ECDSA" is passed in as "keyType" (chosen in ProvTlsServer.selectServerCredentials12).

Sun's implementation parses the "keyType" with

```
        String sigType;
        if (keyType.contains("_")) {
            int k = keyType.indexOf('_');
            sigType = keyType.substring(k + 1);
            keyType = keyType.substring(0, k);
        } else {
            sigType = null;
        }
``` 

result in keyType "ECDHE", and so 

``` 
if (!keyType.equals(certs[0].getPublicKey().getAlgorithm())) {
    continue;
}
``` 

will always continue, though the public key is EC not ECDHE.

See [JSSE Names](https://docs.oracle.com/javase/8/docs/technotes/guides/security/StandardNames.html#jssenames) There "Additional JSSE Standard Names", there is a documentation for the supported values of "keyType" in the X509KeyManager . 

> Daemon Thread [TCP-Server-1#1] (Suspended (breakpoint at line 362 in SunX509KeyManagerImpl))	
> 	owns: ProvSSLEngine_9  (id=75)	
> 	SunX509KeyManagerImpl.getAliases(String, Principal[]) line: 362	
> 	SunX509KeyManagerImpl.getServerAliases(String, Principal[]) line: 320	
> 	SunX509KeyManagerImpl.chooseServerAlias(String, Principal[], Socket) line: 269	
> 	SunX509KeyManagerImpl.chooseEngineServerAlias(String, Principal[], SSLEngine) line: 300	
> 	ImportX509KeyManager_5.chooseEngineServerAlias(String, Principal[], SSLEngine) line: 45	
> 	ImportX509KeyManager_5(BCX509ExtendedKeyManager).chooseEngineServerKeyBC(String[], Principal[], SSLEngine) line: 50	
> 	ProvSSLEngine_9(ProvSSLEngine).chooseServerKey(String[], Principal[]) line: 167	
> 	ProvTlsServer.selectServerCredentials12(Principal[], int) line: 988	
> 	ProvTlsServer.selectCredentials(Principal[], int) line: 927	
> 	ProvTlsServer.selectCipherSuite(int) line: 247	
> 	ProvTlsServer(AbstractTlsServer).getSelectedCipherSuite() line: 431 [local variables unavailable]	
> 	ProvTlsServer.getSelectedCipherSuite() line: 529	
> 	TlsServerProtocol.generateServerHello(ClientHello) line: 570	
> 	TlsServerProtocol.handleHandshakeMessage(short, HandshakeMessageInput) line: 902	
> 	TlsServerProtocol(TlsProtocol).processHandshakeQueue(ByteQueue) line: 635	
> 	TlsServerProtocol(TlsProtocol).processRecord(short, byte[], int, int) line: 524	
> 	RecordStream.readFullRecord(byte[], int, int) line: 207	
> 	TlsServerProtocol(TlsProtocol).safeReadFullRecord(byte[], int, int) line: 830	
> 	TlsServerProtocol(TlsProtocol).offerInput(byte[], int, int) line: 1210	
> 	TlsServerProtocol(TlsProtocol).offerInput(byte[]) line: 1178	
> 	ProvSSLEngine_9(ProvSSLEngine).unwrap(ByteBuffer, ByteBuffer[], int, int) line: 464	
> 	ProvSSLEngine_9(SSLEngine).unwrap(ByteBuffer, ByteBuffer) line: 679	
> 	SslHandler$SslEngineType$3.unwrap(SslHandler, ByteBuf, int, ByteBuf) line: 296	
> 	SslHandler.unwrap(ChannelHandlerContext, ByteBuf, int) line: 1342	
> 	SslHandler.decodeJdkCompatible(ChannelHandlerContext, ByteBuf) line: 1235	
> 	SslHandler.decode(ChannelHandlerContext, ByteBuf, List<Object>) line: 1284	
> 	SslHandler(ByteToMessageDecoder).decodeRemovalReentryProtection(ChannelHandlerContext, ByteBuf, List<Object>) line: 507	
> 	SslHandler(ByteToMessageDecoder).callDecode(ChannelHandlerContext, ByteBuf, List<Object>) line: 446	
> 	SslHandler(ByteToMessageDecoder).channelRead(ChannelHandlerContext, Object) line: 276	
> 	DefaultChannelHandlerContext(AbstractChannelHandlerContext).invokeChannelRead(Object) line: 379	
> 	AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext, Object) line: 365	
> 	DefaultChannelPipeline$HeadContext(AbstractChannelHandlerContext).fireChannelRead(Object) line: 357	
> 	DefaultChannelPipeline$HeadContext.channelRead(ChannelHandlerContext, Object) line: 1410	
> 	DefaultChannelPipeline$HeadContext(AbstractChannelHandlerContext).invokeChannelRead(Object) line: 379	
> 	AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext, Object) line: 365	
> 	DefaultChannelPipeline.fireChannelRead(Object) line: 919	
> 	NioSocketChannel$NioSocketChannelUnsafe(AbstractNioByteChannel$NioByteUnsafe).read() line: 166	
> 	NioEventLoop.processSelectedKey(SelectionKey, AbstractNioChannel) line: 719	
> 	NioEventLoop.processSelectedKeysOptimized() line: 655	
> 	NioEventLoop.processSelectedKeys() line: 581	
> 	NioEventLoop.run() line: 493	
> 	SingleThreadEventExecutor$4.run() line: 986	
> 	ThreadExecutorMap$2.run() line: 74	
> 	Thread.run() line: 831

**Comment by peterdettman** [comment]
Yes, you can't use non-BCJSSE KeyManager with BCJSSE. It's not clear here why that is even happening if you have configured ssl.KeyManagerFactory.algorithm=PKIX and have BCJSSE at higher priority than SunJSSE.

Are you explicitly trying to use the SunX509 KeyManagerFactory?

**Comment by boaks** [comment]
My setup for the KeyManager was:

```
	String algorithm = Security.getProperty("ssl.KeyManagerFactory.algorithm");
	KeyManagerFactory kmf = KeyManagerFactory.getInstance(algorithm);
	kmf.init(store, keyPassword);
	return kmf.getKeyManagers();
```

but I setup "ssl.KeyManagerFactory.algorithm" at the BouncyCastleJsseProvider. I changed it now to 

```
Security.setProperty("ssl.KeyManagerFactory.algorithm","PKIX");
Security.setProperty("ssl.TrustManagerFactory.algorithm","PKIX");
```

And now that works for TLS. Thanks!

I guess, every other provider, which now access that "changed" KeyManager is damned to fail then, though changing the value range of an argument is equivalent to change the API itself and so breaks the X509KeyManager API. Are there any arguments, why that break is required?

**Comment by boaks** [comment]
Anyway: ECDSA works, thanks!

**Comment by boaks** [comment]
Just to ensure, that I understand that well:

The intention of the Bouncy Castle is to use 
- the Sun's "keyTypes" for the client-functions ,
- the "ECDHE_ECDSA" and "ECDHE_RSA" "keyTypes" only for the server-functions

Right?

**Comment by peterdettman** [comment]
For a long time we aimed for compatibility with SunJSSE, including the KeyManager API, but eventually we found issues that were impossible to workaround. I'll list a few below, but note that I haven't checked these things recently, so it's possible (though unlikely) that one or more of them have changed.

1. The SunJSSE KeyManager implementations don't distinguish "RSA" credentials for signing vs encryption usage. So the SSLContext can't specify that it is looking for RSA signing credentials (e.g. for ECDHE_RSA key exchange) vs RSA encryption credentials (i.e. for RSA key exchange). Indeed if you ask for an "RSA" keyType, you will get the first otherwise-valid credentials where the certificate has KeyUsage of digitalSignature AND/OR keyEncipherment. This leads to lots of problems which I suppose users mostly avoid by having only RSA credentials with both KeyUsages. However best practice (and e.g. a FIPS requirement) is NOT to mix usages like this. If you try to keep separate RSA credentials for signing vs encryption, then these implementations return one or the other, somewhat arbitrarily (first found) because you can't even specify which one you want (and obviously therefore the implementation is ignoring the distinction). Note that SunJSSE has dropped its FIPS mode support.

2. Likewise, although less seriously, EC credentials must have both digitalSignature AND keyAgreement KeyUsage set, even though more than likely static ECDH cipher suites are not enabled (in BCJSSE we don't even expose support for them) and you have no other reason to add keyAgreement KeyUsage.

3. With the addition of RSASSA-PSS signature algorithms in RFC 8446 (TLS 1.3 but also can be used backwardly to 1.2), the RSASSA-PSS name became overloaded in a way that can't distinguish properly between the 6 different PSS signature algorithms, which have special rules that the KeyManager can't apply if it can't distinguish them. This issue also affects the "callbacks" from the KeyManager via SSLSession to get the local/peer signature algorithms (another "stringly-typed" API).

4. There are issues around the curve-restrictions (NamedGroup constraints) that apply to some signature algorithms when TLS 1.3 is negotiated. This would be a bit complicated to explain here in detail.

5. If you ask e.g. for "RSA" then the SunJSSE implementations will return even expired credentials, or one with mismatching SNI name (although it prefers perfect matches). But what if you have an unexpired ECDSA certificate that you could be using? Well, SSLContext only asks for these one at a time (for chooseServerAlias), so if you consider RSA first, you may end up negotiating an ECDHE_RSA cipher suite using expired RSA credentials, instead of ECDHE_ECDSA that you could have negotiated with unexpired ECDSA credentials. We have implemented our own method that allows to ask for all keyTypes at once, and therefore the priorities can be applied across all potential cipher suites, leading to better credential selection.

I think those are the major ones, though I might have missed something since this was not recent work.

**Comment by peterdettman** [comment]
> Just to ensure, that I understand that well:
> 
> The intention of the Bouncy Castle PKIX KeyManager implementation is to use
> 
> * the Sun's "keyTypes" for the client-functions ,
> * the "ECDHE_ECDSA" and "ECDHE_RSA" "keyTypes" only for the server-functions
> 
> Right?

We also require BCJSSE KeyManager for client-side, though we may not have changed the particular keyType strings used there (all client credentials are unambiguously signing credentials). Note that we also support "Ed25519" and "Ed448" in all JDK versions. SunJSSE appears to have added "EdDSA" as a keyType from JDK 17 - I don't really see how that is sufficient.

**Comment by boaks** [comment]
Thanks for your answer!

> we may not have changed the particular keyType strings used there

Thanks, that's also my experience.

> Note that we also support "Ed25519" and "Ed448" in all JDK versions. SunJSSE appears to have added "EdDSA" as a keyType

I detected that some days/weeks ago.

**Comment by boaks** [comment]
> I think those are the major ones

Sure, the old Sun APIs are not that useful for new/updated crypto stuff.
I chose to put an helper between Sun's stuff and Californium's more specific ECC support. That reduces the KeyManager function mainly to provide a "preselection of aliases" and then to the effective selection is done in that helper. It's also not a perfect solution and more a work around.

**Comment by peterdettman** [comment]
One more improvement we made is that our methods return the credentials from the KeyManager directly, not just the alias - then requiring a second call to actually fetch that alias.
