### ISSUE TITLE
AKI handling broken in 1.70?

### ISSUE THREAD

**Issue by golbi** [bcgit/bc-java#1082]
Hi,

It seems to me that AKI handling was broken with this change:
https://github.com/bcgit/bc-java/commit/911e5fae52b970d25761c55b30a5eb77c6ba09bd#r62192345

To repeat my source code comment, my concern is that if there are two potential parent certs with matching subject, but with two different keyIds set, and the checked cert sets AKI with key id of one of those, we will always run into error of conflicting trust anchors when building a cert path for the checked cert.

May I get some comment on the intention of this change? Am I missing something here?

**Comment by dghgit** [comment]
It was a bug fix... so this sounds like we're in "dammed if you do, dammed if you don't." The problem is that setting the subjectKeyId in the selector is actually the equivalent of mandating it's presence.

If I read correctly the serial number is not set in the AKI and just the subject and the subject key id is? The way out of this might be to make use of the keyID if serial is null. I can see the sense in that, and it wouldn't trigger the original issue we were trying to deal with.

**Comment by dghgit** [comment]
This change should show up on github shortly. I'll be doing another beta release in a couple of days - it will show up in 171b04 and later.

**Comment by dghgit** [comment]
This is now up in https://www.bouncycastle.org/betas 171 b04 or later.

**Comment by dghgit** [comment]
Assumed now working.
