### ISSUE TITLE
Tag representing attribute certificate in CertificateChoices are apparently not checked against the certificate version

### ISSUE THREAD

**Issue by zambonin** [bcgit/bc-java#1108]
Hello,

the ASN.1 structure `CertificateChoices`, as described in RFC 5652 [1], shows that attribute certificates are stored in different tags according to their versions:
```
CertificateChoices ::= CHOICE {
     certificate Certificate,
     extendedCertificate [0] IMPLICIT ExtendedCertificate,  -- Obsolete
     v1AttrCert [1] IMPLICIT AttributeCertificateV1,        -- Obsolete
     v2AttrCert [2] IMPLICIT AttributeCertificateV2,
     other [3] IMPLICIT OtherCertificateFormat }
```
but it appears that `CMSSignedHelper#getAttributeCertificates(ASN1Set)` [2] does not check the tag number according to the version of the attribute certificate in `AttributeCertificateInfo`.

Unfortunately, I cannot provide a test artifact to confirm this (the file I received has private information), but if my understanding is correct and this is indeed a shortcoming, I am available to readily test possible fixes.

[1] https://datatracker.ietf.org/doc/html/rfc5652#page-49
[2] https://github.com/bcgit/bc-java/blob/master/pkix/src/main/java/org/bouncycastle/cms/CMSSignedHelper.java#L171

**Comment by dghgit** [comment]
Thanks for the report. This is now fixed in https://www.bouncycastle.org/betas 171b13 or later.

**Comment by zambonin** [comment]
Thanks for the commit. However, what happens if a `v1AttrCert` is inside a tag `[2]` or vice-versa (`v2AttrCert` and `[1]`)?

**Comment by dghgit** [comment]
It'll accept it. Not strictly correct, but it doesn't seem like a good reason for rejecting the message. I'm happy to discuss if you think it's likely to be a problem.

**Comment by dghgit** [comment]
Sorry I missed this one... I'd either throw an exception or pass it back through and let someone else deal with it. There's been some unexpected consequences over the last few years due to code ignoring things that are out of place - I can't immediately think of anything in this case myself, but someone more dedicated might later. The method on CMSSignedData just says getAttributeCertificates() so merging the two tags seems to make sense - throwing an exception if someone has mis-tagged an attribute certificate in this context does seem like a bit of an over reaction. I'll admit there is always a bit of a balancing act between being "as useful as possible" and "as rigorousness as possible" - if it did turn out to be necessary to do this maybe a "strict mode" for getAttributeCertificates() would be the way to go.
