### ISSUE TITLE
FIPS TLS sending v1 frame for tlsv1.2 client hello

### ISSUE THREAD

**Issue by chris-kiick-sp** [bcgit/bc-java#1118]
We are seeing an issue where bc-fips tls client hello is rejected (connection closed) because in the client hello, the client version is TLSv1, even though the protocol version is 1.2.  We have specifically disabled tlsv1 and tlsv1.1 in java.security, but it still sends v1 in the client hello.

![Screen Shot 2022-02-22 at 12 50 50 PM](https://user-images.githubusercontent.com/43998532/155199082-eee8eedd-d178-4aea-ae3f-d8a58cc6cbd8.png)
 
In java.security:
jdk.tls.client.protocols="TLSv1.2"
jdk.tls.disabledAlgorithms=SSLv3, TLSv1, TLSv1.1, RC4, DES, MD5withRSA, DH keySize < 1024, EC keySize < 224, DES_EDE_CBC, anon, NULL

Jars: bc-fips-1.0.2.jar    bcpkix-fips-1.0.4.jar       bctls-fips-1.0.10.jar bcpg-fips-1.0.4.jar  bcpqc-addon-fips-1.0.0.jar

I know that this is not the latest version, however, the code looks the same in 1.0.12.2. (TlsClientProtocol.java line 1749). I've tried updating but get other errors related to incompatible trust/key store algorithms.

The RFC for TLSv1.2 states that the client version should be 1.2, even for negotiating different versions (IETF RFC5246 appendix E.1). https://datatracker.ietf.org/doc/html/rfc5246#appendix-E

Is there a work-around or a fix for this?

**Comment by peterdettman** [comment]
I think you are confused between `TLSPlaintext.version`, which is in this example set to 0x0301 (TLSv1), and `ClientHello.client_version`, which is set to TLS 1.2 per the screenshot you provided. I call your attention particularly to these paragraphs of RFC 5246 Appendix E.1:

>    Earlier versions of the TLS specification were not fully clear on
>    what the record layer version number (TLSPlaintext.version) should
>    contain when sending ClientHello (i.e., before it is known which
>    version of the protocol will be employed).  Thus, TLS servers
>    compliant with this specification MUST accept any value {03,XX} as
>    the record layer version number for ClientHello.
> 
>    TLS clients that wish to negotiate with older servers MAY send any
>    value {03,XX} as the record layer version number.  Typical values
>    would be {03,00}, the lowest version number supported by the client,
>    and the value of ClientHello.client_version.  No single value will
>    guarantee interoperability with all old servers, but this is a
>    complex topic beyond the scope of this document.

Therefore a TLS 1.2 server MUST accept {03,01} as the record layer version number.

I assume you are seeing handshake failures of some kind. Are you sure that it is the version number causing the problem? What type of alert is the server raising? Do you know what software is running on the server and is it under your control so that you could collect logs?

**Comment by chris-kiick-sp** [comment]
Thanks for the reply. We have confirmed your analysis.  You nailed it. The client hello included a hostname extension which caused the server to drop the connection. That it correlated exactly with the plaintext.version was a red herring.
