### ISSUE TITLE
jarsigner tells there is no valid certifacation path for bc* artifacts 

### ISSUE THREAD

**Issue by mickaelistria** [bcgit/bc-java#1193]
```
$ jarsigner -verify -verbose bcpg-jdk18on-1.71.jar 


- Signed by "CN=Legion of the Bouncy Castle Inc., OU=Java Software Code Signing, O=Oracle Corporation"
    Digest algorithm: SHA-256
    Signature algorithm: SHA256withDSA, 2048-bit key
  Timestamped by "CN=DigiCert Timestamp 2022 - 2, O="DigiCert, Inc.", C=US" on Wed Mar 30 23:07:56 UTC 2022
    Timestamp digest algorithm: SHA-256
    Timestamp signature algorithm: SHA256withRSA, 4096-bit key

jar verified.

Warning: 
This jar contains entries whose certificate chain is invalid. Reason: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Re-run with the -verbose and -certs options for more details.

The signer certificate will expire on 2027-01-25.
The timestamp will expire on 2033-03-15.
```
This reduces the trust one can put in the artifact. Would it be possible to get the `"CN=Legion of the Bouncy Castle Inc., OU=Java Software Code Signing, O=Oracle Corporation"`  signed by one of the usual root certificates that are available by default in usual JRE distributions.

**Comment by dghgit** [comment]
It's the same certificate the provider is signed with, which is a JCE trusted certificate, a certificate with a much better provenance than any code signing certificate as it is actually hard coded in the JVM. If you need a code signing certificate it is better to have your own, that way you can sign your jars, and counter sign the BC jars with the same certificate. Some application loaders will insist on this in any case.

**Comment by dghgit** [comment]
I don't believe it can be. There's a lot of baggage behind the JCE signing certificate. You can verify it is properly signed by loading the provider into an Oracle or IBM JVM.

**Comment by merks** [comment]
There is this stackoverflow question about the topic

https://stackoverflow.com/questions/20218467/what-is-jce-code-signing-ca

It draws attention to this page with further details.

https://www.oracle.com/java/technologies/javase/getcodesigningcertificate.html

So, as I understand it, a jar that uses the Java Cryptography Extension framework must be signed by a "JCE" certificate, otherwise it won't function.  But that certificate is by intent not one that can generally be used for code signing which requires a certificate rooted on a "normal" trusted certificate.

**Comment by dghgit** [comment]
Yep, that is correct. I'm going to close this one as it appears the original issue is now resolved. It does seem clear that this may be something we need to revisit. It's a bit awkward, we'd really need a 5 year certificate, it looks like the current market only goes up to 3.

**Comment by merks** [comment]
The artifacts come this way from maven central with only a jce signature.  This is intended. It not a problem therefore there is no solution.

**Comment by SumitPuri1112** [comment]
> The artifacts come this way from maven central with only a jce signature. This is intended. It not a problem therefore there is no solution.

But our vulnerability scan report marks it stating **signing process abuses** in this jar.

**Comment by merks** [comment]
The scanner sounds like the problem that needs fixing.  In any case, the jar comes this way from maven  central so you can go upstream to the source project if to wish.

orbit provides these and pgp signs them

https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/table.html

that page provides links to maven central 

eclipse no longer jar signs artifacts from maven central that are provided as OSGi bundles so you are in the wrong place to ask about these artifacts.

**Comment by dghgit** [comment]
Yes, the scanner is the problem. The BC jars are signed using a JCE signing key - the trust anchor for which is embedded in the JVM, not the cacerts file. It's for internal use only, so none of the tools can get access to it, which is why they complain about the certification path. The vulnerability scanning tool should be aware of this - this requirement for JCE providers has existed since Java 4, it is hardly new.
