### ISSUE TITLE
GF2Polynomail: CWE 331 Insufficient Entropy

### ISSUE THREAD

**Issue by RHJTX** [bcgit/bc-java#1260]
Just started using the bcprov-jdk18on-1.72.jar
Our CI/CD pipeline runs a Veracode scan on every develop build and we're getting this High flaw reported.
https://cwe.mitre.org/data/definitions/331.html

I'm assuming it is a false positive, but I need something to propose for mitigation.

Have there been other such reports?
I appreciate any pointers on what I should share with Veracode.
![CWE331-GF2Polynomial](https://user-images.githubusercontent.com/116095644/196470873-06bf8d2f-aa0a-4647-911e-1d34fa6fbfe6.png)

**Comment by dghgit** [comment]
First time we've heard this one. 

In this case the usage is not security relevant, just mathematically. My guess would be it's triggering now (it's actually a very hold class which their tool would have seen before) is because of the migration to the legacy package (so the tool probably thinks it's something recently added, as opposed to something that's been there for 10+ years).
