### ISSUE TITLE
org.bouncycastle.asn1.ASN1Private class existed in 1.69 no longer exists

### ISSUE THREAD

**Issue by dushi792** [bcgit/bc-java#1290]
Hi Bouncy Castle team,
I recently found the class `org.bouncycastle.asn1.ASN1Private` previous existed in `1.69` no longer exists in latest code base.
There is still a doc for this class in 1.69 version [here](https://javadoc.io/static/org.bouncycastle/bcprov-jdk15on/1.69/org/bouncycastle/asn1/ASN1Private.html)
The project I am working on is depending on this ASN1Private class. Can anyone help explain why this class is removed and if there is any solution for replacement? Thank you!

**Comment by peterdettman** [comment]
All types of tagged object (CONTEXT, APPLICATON, PRIVATE) are now handled by `ASN1TaggedObject` and its subclasses (or `ASN1TaggedObjectParser` when parsing).

Instead of creating a `DERPrivate`, create a `DERTaggedObject` (or BER, DL) using a constructor that accepts a `tagClass`, and pass `BERTags.PRIVATE` as the tag class.

When parsing, an `ASN1TaggedObject` subclass will be returned for the PRIVATE-tagged encoding. Check its tag class and tag number to make sure it matches what you are expecting e.g. using `ASN1TaggedObject.hasTag`, before accessing the base object. There are also a whole range of utility methods in `ASN1Util` to simplify checking/extracting tagged values.

`DERPrivateTest` also survives and was converted from using `ASN1Private` to using `ASN1TaggedObject`, so may be helpful.
