### ISSUE TITLE
Often long BouncyCastleFipsProvider lock in getDefaultSecureRandom()

### ISSUE THREAD

**Issue by marnix** [bcgit/bc-java#1431]
The context is a Java 8 JVM where both the BCFIPS and BCJSSE providers are registered (and SunJSSE is not), not in approved-only mode and FIPS mode respectively, using bc-fips-1.0.2.3.jar and bctls-fips-1.0.14.1.jar.

In deployments with a lot of traffic, we see quite some wait time for the registered BouncyCastleFipsProvider's lock.  And a large part of these occur while decrypting TLS packets, in `RecordStream.decodeAndVerify()` \-> `TlsAEADCipher.decodeCipherText()` \-> `JceAEADCipherImpl.init()`.

And the ones that seem most time-consuming, are those that go from `JceAEADCipherImpl.init()` to `BouncyCastleFipsProvider.getDefaultSecureRandom()`, for example in the following stack trace:
```
	at java.lang.Throwable.fillInStackTrace(Native Method)
	at java.lang.Throwable.fillInStackTrace(Throwable.java:784)
	-  locked java.lang.IllegalStateException@67772e0c
	at java.lang.Throwable.<init>(Throwable.java:266)
	at java.lang.Exception.<init>(Exception.java:66)
	at java.lang.RuntimeException.<init>(RuntimeException.java:62)
	at java.lang.IllegalStateException.<init>(IllegalStateException.java:55)
	at org.bouncycastle.crypto.CryptoServicesRegistrar.getSecureRandom(Unknown Source)
	at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider.getDefaultSecureRandom(Unknown Source)
	at org.bouncycastle.jcajce.provider.BaseCipher.engineInit(Unknown Source)
	at org.bouncycastle.jcajce.provider.BaseCipher.engineInit(Unknown Source)
	at javax.crypto.Cipher.init(Cipher.java:1540)
	at org.bouncycastle.tls.crypto.impl.jcajce.JceAEADCipherImpl.init(JceAEADCipherImpl.java:108)
	at org.bouncycastle.tls.crypto.impl.TlsAEADCipher.decodeCiphertext(TlsAEADCipher.java:299)
	at org.bouncycastle.tls.RecordStream.decodeAndVerify(RecordStream.java:253)
	at org.bouncycastle.tls.RecordStream.readFullRecord(RecordStream.java:204)
	at org.bouncycastle.tls.TlsProtocol.safeReadFullRecord(TlsProtocol.java:922)
	at org.bouncycastle.tls.TlsProtocol.offerInput(TlsProtocol.java:1364)
	at org.bouncycastle.jsse.provider.ProvSSLEngine.unwrap(ProvSSLEngine.java:481)
	-  locked org.bouncycastle.jsse.provider.ProvSSLEngine_8@52d8950d
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:626)
[...snipped some of our own code...]
	at java.lang.Thread.run(Thread.java:750)
```

So from the bctls-fips-1.0.14.1.jar and bc-fips-1.0.2.3.jar source code, what seems to happen, is that for every decrypted packet `Cipher.init()` is called; that always calls `BouncyCastleFipsProvider.getDefaultSecureRandom()`; that always calls `CryptoServicesRegistrar.getSecureRandom()`; that by default always throws an `IllegalStateException`; and _inside `catch (IllegalStateException e)` the caller `BouncyCastleFipsProvider.getDefaultSecureRandom()` then always creates its own `SecureRandom`, keeping the lock all the time:_
```java
        try
        {
            defRandom = CryptoServicesRegistrar.getSecureRandom();
        }
        catch (IllegalStateException e)
        {
            // See SP 800-90A R1 8.6.7 for setting of Nonce - at least 1/2 security strength bits
            synchronized (this)
            {
                if (providerDefaultRandom == null)
                {
                    SecureRandom sourceOfEntropy = getDefaultEntropySource();

                    // we set providerDefault here as we end up recursing due to personalization string
                    providerDefaultRandom = providerDefaultRandomBuilder
                        .fromEntropySource(sourceOfEntropy, true)
                        .setPersonalizationString(generatePersonalizationString())
                        .build(sourceOfEntropy.generateSeed((providerDefaultSecurityStrength / (2 * 8)) + 1), true, Strings.toByteArray("Bouncy Castle FIPS Provider"));
                }

                defRandom = providerDefaultRandom;
            }
        }
```

Is this expected behavior?  Or are we expected to call `CryptoServicesRegistrar.setSecureRandom()` to avoid all this exception-throwing and `SecureRandom`-creating?

We could find no documentation about that last method.

----

Note that we tried to set a default `SecureRandom` in `CryptoServicesRegistrar`, namely `SecureRandom.getInstance("DEFAULT", "BCFIPS")`, and that reduced the lock time by a lot, but then things started to fail in BCFIPS approved-only mode threads, with `FipsUnapprovedOperationError: FIPS SecureRandom security strength not as high as required for operation: RSA`.

**Comment by dghgit** [comment]
Something does not sound right... the setting of providerDefaultRandom should only occur once for a provider so the behavior described makes it sound like multiple providers are being created. 

How is the BCJSSE configured?

I'm not entirely sure what's going on with the use of setSecureRandom either, but I thought I should cross the BCJSSE off the list first.

**Comment by marnix** [comment]
"How is the BCJSSE configured?" Could you clarify?

We do set a few properties for BCJSSE and BCFIPS (will comment with details tomorrow) but nothing around SecureRandom.  (And we tell the JDK via java.security to use urandom and ...NonBlocking..., to prevent entropy issues on our Linux VMs.)

**Comment by dghgit** [comment]
For FIPS you would usually configure it as fips:BCFIPS in java.security - in this case it would be in FIPS mode and using the BCFIPS provider. See section 2.1.1 of https://downloads.bouncycastle.org/fips-java/BC-FJA-(D)TLSUserGuide-1.0.15.pdf (this would apply to 14.1 as well).

One thing urandom and NonBlocking is not FIPS compliant, there's no point in using FIPS mode if you're using these - the application is not FIPS compliant the moment it boots up. It's possible to configure a DRBG chain in the FIPS provider as described with the HYBRID mode in section 2.3 https://downloads.bouncycastle.org/fips-java/BC-FJA-UserGuide-1.0.2.pdf 

I'd also recommend looking at rng-tools or haveged to assist with this as well (HYBRID's fine once you're up and running, but a lack of entropy can cause a pause at boot time as well).

**Comment by peterdettman** [comment]
No randomness is needed for this operation, so it's at least an issue that the provider thinks it should initialize one at all. Presumably the one-time creation of providerDefaultRandom is not a main contributor, although it would preferably use the static singleton pattern instead of synchronization if possible. Finally the exception-as-return-value should be replaced with something like a tryGetSecureRandom.

However all those things require FIPS provider updates which is a slow turnaround.

https://github.com/bcgit/bc-java/commit/88101267d74d7b63cd92ffdab86c2fbba81792f6 started passing null as the random (instead of a JCE default - and therefore non-FIPS - SecureRandom). That would explain why this has only recently surfaced.

Since BCJSSE has a SecureRandom already available anyway I have changed the code to pass that instead of null. This should at least work around the issue until we get a chance to update the provider.

Just a note in case the original report is misdiagnosed in some way, there was a nearby performance issue addressed by https://github.com/bcgit/bc-java/commit/b25b441db071fd618a351446a4b9d6570dc05906 - that fix would not be present in 1.0.14.1 .

**Comment by marnix** [comment]
> Something does not sound right... the setting of providerDefaultRandom should only occur once for a provider so the behavior described makes it sound like multiple providers are being created.

We are pretty sure we are creating only one BouncyCastleFipsProvider instance.

Also, I see no evidence (in the bc-fips-1.0.2.3.jar and bctls-fips-1.0.14.1.jar source code) that `org.bouncycastle.crypto.CryptoServicesRegistrar.defaultSecureRandom` is ever updated, because I see no calls to `CryptoServicesRegistrar.setSecureRandom()`.  So (as long as we don't do anything explicit), `CryptoServicesRegistrar.getSecureRandom()` will always return `null`?

In other words, I see no evidence for your "should only occur once"?

> How is the BCJSSE configured?
> 
> I'm not entirely sure what's going on with the use of setSecureRandom either, but I thought I should cross the BCJSSE off the list first.

> For FIPS you would usually configure it as fips:BCFIPS in java.security - in this case it would be in FIPS mode and using the BCFIPS provider. See section 2.1.1 of https://downloads.bouncycastle.org/fips-java/BC-FJA-(D)TLSUserGuide-1.0.15.pdf (this would apply to 14.1 as well). Note: this isn't quite the same as having the module in FIPS mode - it just restricts the JSSE to what is acceptable in SP 800-52.

We have the same code base running BCJSSE from bctls-fips.jar in both in FIPS mode (so 'SP 800-52 mode' as you say, so with `fips:BCFIPS`, which we're aware is different from running as a FIPS validated module), and elsewhere in its default non-FIPS mode.  This reported issue we encountered in non-FIPS mode (and I don't think we tested it in non-FIPS mode).

Except for that, we run BCJSSE with only

- Security property `ssl.KeyManagerFactory.algorithm=PKIX`
- System property `org.bouncycastle.jsse.client.assumeOriginalHostName=true`

**Comment by dghgit** [comment]
The original comment said you were seeing "that always calls CryptoServicesRegistrar.getSecureRandom(); that by default always throws an IllegalStateException; and inside catch (IllegalStateException e) the caller BouncyCastleFipsProvider.getDefaultSecureRandom() then always creates its own SecureRandom, keeping the lock all the time:"

I gather I wasn't clear about what I said. The providerDefaultRandom variable is a local field in the provider class. Ordinarily you'd expect this to be set once unless multiple threads were making multiple copies of the provider's non-volatile memory at the same time and consistently creating new SecureRandoms, I'm not saying this is impossible, but I can't say we've seen it before - the setting of the variable is being done under synchronized so by rights should actually be done on the "master copy" of the object. The biggest penalty you should be paying is the exception, again if your application results in a lot of calls to getDefaultSecureRandom() - the exception would show up a lot in thread dumps, similar to what is provided in your example but which is not code within the synchronized block as the exception is still being constructed and is not yet caught.

Since you don't have to worry about FIPS compliance, it might be worth trying 1.0.2.4 which avoids the exception throwing, and see how your experience is with that. The only caveat I would add on that is that if you have access to the support program you should use the version available through that, although for these purposes the non-cert version on the BC website is probably close enough to the submitted version.

**Comment by marnix** [comment]
Ah, OK, thanks!  I should have seen that `BouncyCastleFipsProvider.providerDefaultRandom` is only initialized once, so indeed my statement "inside `catch (IllegalStateException e)` the caller `BouncyCastleFipsProvider.getDefaultSecureRandom()` then always creates its own SecureRandom"` was incorrect: That SecureRandom is created only once.

Thanks for letting us know bc-fips-1.0.2.4.jar avoids / will avoid the `IllegalStateException` throwing.

So the biggest issue with the current code might be that exception throwing.

Or it may be that no `if (providerDefaultRandom == null)` check is done before entering `synchronized (this)`?  It seems that doing if-synchronized-if would avoid a lot of locks here, even though they would be short-lived.

Or whatever solution you think best, of course, like @peterdettman wrote, "it would preferably use the static singleton pattern instead of synchronization if possible."

And @peterdettman thanks for letting us know that a new version of BCJSSE will avoid the call to `org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider.getDefaultSecureRandom()` altogether:

> Since BCJSSE has a SecureRandom already available anyway, so I have changed the code to pass that instead of null. This should at least work around the issue until we get a chance to update the provider.

Either of those fixes should solve this issue for us.

**Comment by peterdettman** [comment]
@marnix bctls-fips-1.0.17.jar was just published to the bc-fips-java git repo. It contains the SecureRandom workaround amongst other fixes and features.

**Comment by dghgit** [comment]
Appears completed.
