### ISSUE TITLE
Wrong values for Brainpool Groups in TLS 1.2

### ISSUE THREAD

**Issue by vbrandl** [bcgit/bc-java#1470]
According to [IANA](https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml), these are the values for brainpool groups in TLS:

| Value | Description |
| --- | --- |
| `26` | `brainpoolP256r1` |
| `27` | `brainpoolP384r1` |
| `28` | `brainpoolP512r1` |
| `31` | `brainpoolP256r1tls13` |
| `32` | `brainpoolP384r1tls13` |
| `33` | `brainpoolP512r1tls13` |

I try to connect another server using brainpool keys and mTLS using TLSv1.2. This fails because in the handshake, the values for the `brainpoolP*r1tls13` groups are passed. Attached you can find a screenshot from wireshark. (`0x1f`-`0x21` are `31`-`33`)

![2023-08-09_16-58](https://github.com/bcgit/bc-java/assets/20639051/ddef329a-5fa9-46ec-9061-0bd927859b37)

**Comment by peterdettman** [comment]
The TLS 1.2 you have highlighted in the ClientHello is the legacy version number. If you open the supported_versions extension I expect you will see that you are actually offering TLS 1.3 as well. So it's fine for the client to send brainpool...tls13 in supported_groups.

If you wanted to _also_ send the original brainpool group values so that brainpool can be used when TLS 1.2 is negotiated, then you have to enable them explicitly, using either:

- the "jdk.tls.namedGroups" system property.
- if your JDK version is sufficient, SSLParameters.setNamedGroups (supported in BC's last couple of releases).
- if your JDK is older, BCSSLParameters.setNamedGroups (again only in recent BC releases).

**Comment by vbrandl** [comment]
Thank you very much. This fixed the problem for outgoing connections.

I guess the same property is also evaluated when running a TLS server and wanting to support brainpool groups?

**Comment by vbrandl** [comment]
I forgot to reply. Thanks for the help and it does work now.
