### ISSUE TITLE
DER-encoded CMS SignedData object using CMSSignedDataStreamGenerator

### ISSUE THREAD

**Issue by SkyCrawl** [bcgit/bc-java#1482]
Hello,

in ETSI TS 102 778-3 v1.2.1, and later also ETSI EN 319 142-1 v1.1.1, there is the following requirement:

> A DER-encoded SignedData object as specified in CMS (RFC 3852 [4]) shall be included as the PDF signature in the entry with the key Contents of the Signature Dictionary as described in ISO 32000-1 [1], clause 12.8.1.

A DER-encoded SignedData object can be generated with BouncyCastle, but only using the CMSSignedDataGenerator class, not CMSSignedDataStreamGenerator. I was wondering why and whether it would be possible to bring support for DER-encoded SignedData objects to CMSSignedDataStreamGenerator as well.

**Comment by peterdettman** [comment]
DER encoding includes definite lengths at the start of encodings, which means that it needs to know the exact length of the output before it starts producing any. The purpose of the CMS stream generators is to produce output directly (i.e. without keeping in memory a full copy of the data), which is fundamentally incompatible with DER in the general case.

**Comment by bsanchezb** [comment]
Hello @peterdettman,

I would like to ask if it is feasible to extend _CMSSignedDataStreamGenerator_ functionality to create DER-encoded CMS, provided that the size of the encapsulated content info is provided in advance?

This limitation on creating only BER-encoded signatures with _CMSSignedDataStreamGenerator_ creates problems on augmentation of CAdES signatures containing archiveTimestampV2, which message-imprint computation is dependent on the data encoding within the signature (see #1983 for more information).

Currently, if we try to extend a DER-encoded signature with a _CMSSignedDataStreamGenerator_, the produced signature is generated using a BER-encoding, which breaks the available archiveTimestampV2.

Provided that the size of the original ContentInfo and other properties is known in advance, would it be possible to generate all the required DER tags on the fly using _CMSSignedDataStreamGenerator_ or an alternative implementation, so the provided signature result is DER encoded or encoded in the same way as the original signature provided to the augmentation service?

**Comment by bsanchezb** [comment]
@dghgit we cannot use the CMSSignedDataGenerator class when streaming is required, for instance for signing large files.

To provide you with more context, we deliver two implementations for CMS signing: one based on in-memory computation and one on streams only (see [dss-cms-object](https://github.com/esig/dss/tree/master/dss-cms-object) and [dss-cms-stream](https://github.com/esig/dss/tree/master/dss-cms-stream) respectively). Because of the aforementioned limitations, the _dss-cms-stream_ module has a limited functionality, e.g. not able to augment certain signatures (where the original coding shall be preserved).

We would like to align both implementations so users that choose to work with the streams, they do not face any unexpected limitations.

**Comment by DemiMarie** [comment]
What about using off-heap memory or a temporary disk file?  That will not be fast, but it should at least work.

**Comment by dghgit** [comment]
With the try-with-resources, the words are in the wrong order "there is a not-easy-to-notice weakness in CMSSignedDataStreamGenerator. If you use a try-with-resources..." should read "there is a not-easy-to-notice weakness in try-with-resources. If you use a CMSSignedDataStreamGenerator..." It's the defined behavior of the language construct and any exception thrown in the block will result in the same behavior. Apart from the BC API pre-dating try-with-resources, try-with-resources was primarily introduced to prevent accidental resource leakage - in other respects it is a "happy path" construct though and if used the developer concerned needs to keep in mind what happens when it's not all "puppies, ponies, and rainbows" when the try is exited.

I've added setEncoding() to CMSSignedDataStreamGenerator in a similar way to what has been done for CMSSignedDataGenerator. It will work fine for detached signatures, but may have memory issues for encapsulated as it (currently) has to rely on a ByteArrayOutputStream to cache the data, the reason I ended up there is it isn't just the data you need the size for if you're going to produce definite-length encoded data, it's everything before and after it as well... a bit more complicated than I currently have time for.

**Comment by dghgit** [comment]
Okay, a "generate" method has been added to allow generation of extremely long encapsulated data in definite length format. The reason for generate() rather than further leveraging open() is some signature algorithms do not have stable length signatures, so to use definite length the signature value needs to be known first (which means the data needs to be parsed twice). Now up on https://www.bouncycastle.org/betas
