### ISSUE TITLE
ByteUtils.xor method not migrated to org.bouncycastle.util.Arrays.

### ISSUE THREAD

**Issue by 3mmasun** [bcgit/bc-java#1498]
We are current using the xor in org.bouncycastle.pqc.legacy.math.linearalgebra.ByteUtils
Since the method has been deprecated and advice is to use use org.bouncycastle.util.Arrays, I would like to request following static methods to be migrated also
- String toHexString(byte[] input, String prefix, String seperator)
- String toHexString(byte[] input)
- byte[] xor(byte[] x1, byte[] x2)

Version: org.bouncycastle:bcprov-jdk18on:1.72

**Comment by peterdettman** [comment]
I created some xor methods in org.bouncycastle.util.Bytes class, however none of them return a newly-allocated result. If you need that I would recommend you just copy the method since it is small.

For toHexString(byte[]) use org.bouncycastle.util.encoders.Hex.toHexString. For the variant taking prefix and separator you would probably be best to copy the method into your code.
