### ISSUE TITLE
Different signature hashes depending on BC version

### ISSUE THREAD

**Issue by philippecade** [bcgit/bc-java#1513]
We are generating a signature with the following code:
```
            CMSSignedDataGenerator generator = new CMSSignedDataGenerator();
            ContentSigner sha1Signer = new JcaContentSignerBuilder("SHA1withRSA")
                    .setProvider("BC").build(getPrivateKey());
            SignerInfoGenerator signerInfoGenerator = new JcaSignerInfoGeneratorBuilder(
                    new JcaDigestCalculatorProviderBuilder().setProvider("BC").build()).setDirectSignature(true)
                    .build(sha1Signer, getPublicKey());
            generator.addSignerInfoGenerator(signerInfoGenerator);
            CMSSignedData signedData = generator.generate(new CMSProcessableByteArray(data), false);
            return signedData.getEncoded();
```
and we noticed with a unit test that the generated signature hash had changed between BC version 1.70 and 1.71 (and 1.76).

I have reviewed the release notes and code changes but still can't figure out why the hashes are different.

Is this a regression or do we need to change some parameters to find the same hashes again?

I made a reproducer here https://github.com/philippecade/bc-359077
- the unit test with fail (using BC 1.76)
- edit the `app/build.gradle` file to enable version 1.70, the unit test will be OK again

**Comment by dghgit** [comment]
The signatures are the same. What's been compared is the ASN.1 encoded SignedData object. The difference here is the API is a bit cleverer about how it encodes things now so it tries to avoid wrapping indefinite-length data in definite-length data.

A look at the ASN.1 dump for both objects shows what's different.

In the old one the stream begins with:

BER Sequence
    ObjectIdentifier(1.2.840.113549.1.7.2)
    BER Tagged [CONTEXT 0]
        BER Sequence
            Integer(1)
            Set
                Sequence
                    ObjectIdentifier(1.3.14.3.2.26)
                    NULL
            BER Sequence
                ObjectIdentifier(1.2.840.113549.1.7.1)

In the new one it's:

Sequence
    ObjectIdentifier(1.2.840.113549.1.7.2)
    Tagged [CONTEXT 0]
        Sequence
            Integer(1)
            Set
                Sequence
                    ObjectIdentifier(1.3.14.3.2.26)
                    NULL
            Sequence
                ObjectIdentifier(1.2.840.113549.1.7.1)
            Set

The difference is due to the EncapsulatedSignedData field, which specifies empty but consists of only a single definite-length item, the ASN.1 object identifier so the encoder has recognised BER data is not required.

That said, if you check the actual signature value, you'll find it's identical in both cases.

**Comment by philippecade** [comment]
Thank you for the detailed answer, all is clear now.
