### ISSUE TITLE
Discrepancy to FIPS-186-4 for Shawe-Taylor Random Prime Generation

### ISSUE THREAD

**Issue by hengxti** [bcgit/bc-java#152]
FIPS 186-4 C.6 Shawe-Taylor Random_Prime Routine states in step 14. that for the recursive call the INPUTSEED shall be used. 
The Bouncycastle implementation uses the PRIMESEED in Routine implSTRandomPrime() in org.bouncycastle.math.Primes.java

https://github.com/bcgit/bc-java/blob/adecd89d33edf278a5c601af2de696f0a6f65251/core/src/main/java/org/bouncycastle/math/Primes.java 
Line 503: 
return new STOutput(BigInteger.valueOf(c64), primeSeed, primeGenCounter); 

Could that be a mistake in the FIPS-186-4 Standard? (I believe it is) The primeSeed seems to be the better choice since it is altered for each recurive call. The path for primes < 32 Bits results in the same hashes using the input seed, therefore all generated 32 Bit primes are equal. This is potentially problematic for the quality of the final prime number

**Comment by peterdettman** [comment]
Line 503 is step 11.2, I think. The recursive call from step 14 is at line 513. I don't think there's any mistake in the standard here, we just noticed (after initial implementation) that "input_seed" wasn't really needed as an extra name, since it's either aliased immediately to "prime_seed", or passed to a recursive call. So we may as well just call the input parameter prime_seed. Note that there is really only a single seed that is updated in-place throughout the algorithm.
