### ISSUE TITLE
PKCS#12 MAC validation fails

### ISSUE THREAD

**Issue by ascn17** [bcgit/bc-java#1875]
A PKCS#12, created by external user with openssl 1.1.x, fails MAC validation using BouncyCastle classes but works fine with Java Keystore. I can't get any details about the failure in BouncyCastle but I've made a small test program that reproduces the problem. It also shows that Java Keystore can parse it. The attached zip-file contains the test program and the problematic PKCS#12. The password is stated in App,java

Can this be a bug in BouncyCastle or is Java Keystore more forgiving in allowing legacy algorithms? I can also mention that the problematic PKCS#12 can only be parsed with openssl 3.x with the "-legacy" option.

[testprog-p12.zip](https://github.com/user-attachments/files/17478228/testprog-p12.zip)

**Comment by roy-basmacier** [comment]
Hello @ascn17,

It seems like the reason why the _isMacValid()_ fails in the example is due to the ASN1 encoding:

expected byte array: 
> 302b301f300706052b0e03021a041498b0dbcc56a918cd83934aeb9b87b0db36ef98e10408e122e36d48aebf2c

calculated byte array:
> 302d3021300906052b0e03021a0500041498b0dbcc56a918cd83934aeb9b87b0db36ef98e10408e122e36d48aebf2c

The difference between the two encoding is the null Parameters in the Algorithm Identifier. BC is writing the null parameters where as the provided encoding is ignoring it in the ASN1 encoding. 

The hash for both are the same:
> 98b0dbcc56a918cd83934aeb9b87b0db36ef98e1

However, BouncyCastle can load the PKCS#12 file provided. It also does a MAC validation when loading the file which validates correctly (it checks the digest rather than the ASN1 sequence).


Here is how I loaded the file:

```Java
Security.addProvider(new BouncyCastleProvider());
KeyStore store = KeyStore.getInstance("PKCS12", "BC");
ByteArrayInputStream stream = new ByteArrayInputStream(Base64.getDecoder().decode(failingP12));
store.load(stream, password);
```
