### ISSUE TITLE
Support $2x$, $2y$, $2b$ Bcrypt hashes

### ISSUE THREAD

**Issue by floragunncom** [bcgit/bc-java#207]
Add support for $2x$, $2y$, $2b$ hashes in org.bouncycastle.crypto.generators.OpenBSDBCrypt
Currently only $2a$ is supported. This is a problem if users generate their hashes for example with "htpasswd -nB -C 12" which emits a $2y$ hash.

With 1.57 i get a 
<pre>
Exception in thread "main" java.lang.IllegalArgumentException: Wrong Bcrypt version, 2a expected.
	at org.bouncycastle.crypto.generators.OpenBSDBCrypt.checkPassword(Unknown Source)
	at ...
</pre>

**Comment by mwcw** [comment]
Hi 

OpenBSDCrypt has been modified to accept 2a,2y and 2b however it can't generate the older versions of 2a that had the security issue.

The 2x version is not supported as it is used to identify faulty 2a digests. We would prefer a user changed the string to 2a explicitly for testing in order to prevent one of these being accepted by mistake.

**Comment by floragunncom** [comment]
Where and when has OpenBSDCrypt been modified to accept 2y and 2b? I tried with latest 1.57 and it did not work?

**Comment by mwcw** [comment]
Sorry it takes a little while for things to sync up.

**Comment by floragunncom** [comment]
thx
