### ISSUE TITLE
How can I use this to encrypt with private key.

### ISSUE THREAD

**Issue by tellmewhattodo** [bcgit/bc-java#317]
I have learned how to encrypt with public key ,and in my case ,I must encrypt something with private key .
I tried only change the PublicKeyFactory to PrivateKeyFactory in the example which is given in this page:
http://www.mysamplecode.com/2011/08/java-rsa-encrypt-string-using-bouncy.html

But it didn't work,and I got a Exception as: 
java.lang.IllegalArgumentException: unknown object in getInstance: org.bouncycastle.asn1.ASN1Integer

Please help me ,pls.

**Comment by bcgit** [comment]
I can't look at the example but my guess is you are using X509EncodedKeySpec. The exception is what I would expect if a direct encoding of an RSA key was passed to a key factory rather than an encoded SubjectPublicKeyInfo. Regardless of the algorithm X509EncodedKeySpec will only work with a full SubjectPublicKeyInfo encoding.
