### ISSUE TITLE
JSSE provider, support for other KeyManager implementations

### ISSUE THREAD

**Issue by pfirmstone** [bcgit/bc-java#325]
Currently a handshake failure occurs when attempting to use KeyManager implementations other than Bouncy Castle's.

Supporting other KeyManager implementations will allow obtaining client certificates from the current Subject, allowing the use of KeyStoreLoginModule for example.

**Comment by dghgit** [comment]
The problem here is there is no standard way for a JSSE provider to talk to a KeyManager - if a KeyManager was implemented which followed the same naming conventions used in the BC KeyManager it would be fine. That said we have been able to improve compatibility in some cases, but it's going to remain an issue.
