### ISSUE TITLE
CVE-2015-6644

### ISSUE THREAD

**Issue by milkotodorov** [bcgit/bc-java#346]
Security issue found in latest 1.59 version: https://nvd.nist.gov/vuln/detail/CVE-2015-6644

**Comment by bcgit** [comment]
We actually picked this up as part of the initial FIPS project. It was fixed in BC 1.55 and is mentioned in the defect list in release notes - we didn't use the same approach as Android which would explain why the code appears to be missing - GCMBlockCipher.getNextCTRBlock() has the check in it. 

Looking at the Android patch it actually appears have a bug in it (non-security related).

**Comment by milkotodorov** [comment]
Thanks!
