### ISSUE TITLE
illegal_parameter(47) on DH key exchange

### ISSUE THREAD

**Issue by pts-danielmanley** [bcgit/bc-java#386]
Hi,

I'm getting TLS handshake failures in JDK14 connecting to hosts like webservices-uat.aeroplan.com -- I'm using BC prov 1.60.  I've seen similar exceptions in validateCertificateRequest() in TlsECDHEKeyExchange and TlsRSAKeyExchange.  I see the the BC code prevents particular certificate types as per the RFC?  Is this a misconfiguration then in the server and I should contact them to fix their setup?

Dan

```
org.bouncycastle.crypto.tls.TlsFatalAlert: illegal_parameter(47)
	at org.bouncycastle.crypto.tls.TlsDHKeyExchange.validateCertificateRequest(TlsDHKeyExchange.java:190)
	at org.bouncycastle.crypto.tls.TlsClientProtocol.handleHandshakeMessage(TlsClientProtocol.java:494)
	at org.bouncycastle.crypto.tls.TlsProtocol.processHandshakeQueue(TlsProtocol.java:456)
	at org.bouncycastle.crypto.tls.TlsProtocol.processRecord(TlsProtocol.java:374)
	at org.bouncycastle.crypto.tls.RecordStream.readRecord(RecordStream.java:222)
	at org.bouncycastle.crypto.tls.TlsProtocol.safeReadRecord(TlsProtocol.java:594)
	at org.bouncycastle.crypto.tls.TlsProtocol.blockForHandshake(TlsProtocol.java:273)
	at org.bouncycastle.crypto.tls.TlsClientProtocol.connect(TlsClientProtocol.java:105)
```

**Comment by peterdettman** [comment]
Short answer: This problem will go away if you move from the legacy TLS API (bcprov*.jar, org.bouncycastle.crypto.tls) to the newer one (bctls*.jar, org.bouncycastle.tls). In most cases that would only require minor changes in your code.

Unfortunately you will need to build it yourself for JDK1.4 since we only ship a jdk15on version. Only the org.bouncycastle.jsse.** classes should have any actual 1.5+ code in them so it should be simple to strip those.

Not all ClientCertificateType's are valid for all key exchanges, but it's a common enough problem that a server just dumps all possible ClientCertificateType's into every CertificateRequest that we decided that failing the handshake was heavy-handed. So in the new API, the TLS client strips invalid options from the CertificateRequest before passing it to TlsAuthentication.getClientCredentials.

**Comment by pts-danielmanley** [comment]
ah ok -- thank you very much for the info.  We're in a very slow process of migrating this system and our partner integrations to jdk8+.  At this time, we've been switching to external stunnels for connections that are just not working out.  We'll evaluate if doing a custom compile is worth it vs hurrying these particular integrations to our newer system where they should just work out of the box.

and thank you to the BC team for making TLS1.2 in JDK14 possible -- HUGE thank you!

**Comment by peterdettman** [comment]
FYI, at some point since this issue was raised we started releasing a bctls-jdk14 jar which is TLS without the BCJSSE provider, for JDK1.4.

**Comment by peterdettman** [comment]
There's a bctls-debug jar that should let you debug better (and give line numbers for the stack trace).

Assuming this alert is actually an alert received from the client side, then you would need to check at the client side (openssl logs) for why it raised an illegal_parameter alert.

Since you tagged this issue related to DH, perhaps the client doesn't accept the DH group the server has selected, in which case you would probably need to configure a different one. However let's see what openssl is complaing about first.
