### ISSUE TITLE
Salt & Hash generated using old version is not working in new version

### ISSUE THREAD

**Issue by sureshpritmani** [bcgit/bc-java#398]
I have generated salt and hash with version older version, (i.e. 1.49) and but it is not getting validated with 1.53 onwards version but getting validated till 1.52 version. And my understanding is it should be 
compatible with all versions.

From release notes, I couldn't identify such change with version 1.53

For reference purpose, I have attached sample text file.
[TestSaltAndHash.txt](https://github.com/bcgit/bc-java/files/2281805/TestSaltAndHash.txt)

**Comment by bcgit** [comment]
The release notes for 1.53 document that SHA-3 was changed to Keccak, to make way for the actual SHA-3. This happened due to a last minute tweak in the algorithm by NIST.

Please do not use BC internal classes in your code, using org.bouncycastle.jcajce.provider.digest.SHA3.DigestSHA3 is simply asking for trouble. If you want to avoid the JCA use KeccakDigest
