### ISSUE TITLE
curve25519 or Ed25519?

### ISSUE THREAD

**Issue by jackzhp** [bcgit/bc-java#399]
In the Curve25519.java, it says 
        this.a = fromBigInteger(new BigInteger(1,Hex.decode("2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA984914A144")));
        this.b = fromBigInteger(new BigInteger(1,Hex.decode("7B425ED097B425ED097B425ED097B425ED097B425ED097B4260B5E9C7710C864")));

However, from wiki, I see a=486662, b=1. Any idea about what is going on here? thanks.

**Comment by peterdettman** [comment]
The constants are different because the Curve25519 class is for the short-Weierstrass form, rather than the usual Montgomery form. This is for historical reasons, in that our older EC code could only work with short-Weierstrass curves. Probably you don't want to try and use this, and we may remove it since it appears to be causing much confusion.

The class org.bouncycastle.math.ec.rfc7748.X25519 is a low-level implementation of X25519 (from RFC 7748); we are currently working to integrate it into the lightweight and JCE/JCA APIs. Similarly for X448, Ed25519, Ed448.
