### ISSUE TITLE
cipher.getProvider() corrupts non-initialized cipher

### ISSUE THREAD

**Issue by rodburgett** [bcgit/bc-java#432]
A call to cipher.getProvider() that occurs between Cipher.getCipher(...) and cipher.init() will corrupt the Cipher instance and cause initialization to fail with InvalidAlgorithmParameterException.

This error was encountered when using a PBE... algorithm.  Repro with other algorithms was not attempted.

To repro:
Take any code that successfully encrypts.  Add 'System.out.println(cipher.getProvider());' between the getCipher and init calls.

The same results were seen with BC v1.52.0 and v1.60.0.

**Comment by bcgit** [comment]
This is actually a JCE method, it doesn't even call to the BC API. The only thing I can think of that would cause an issue like this is that the JCE itself is incorrectly configured - either it can't find something on the classpath, it can't authenticate something on the classpath, or there's a class annotation error due to an insecure class loader being involved or a duplicate class.
