### ISSUE TITLE
CMS signing allows incompatible private/public key pairs

### ISSUE THREAD

**Issue by veselov** [bcgit/bc-java#452]
If I create a signed block using CMSSignedDataGenerator, but I specify private key that was not used for generating the certificate used as a signer info, the operation succeeds. This obviously creates content that can not be validated.
Does that make sense? Should this cause an error during the signing process?

**Comment by bcgit** [comment]
I can see your point... it's a bit of tricky one though. The certificate is actually just used to generate the SID (in the typical case this will also mean the public key is the one to use for verification, but there's bound to be someone out there that is using the SID for their own purposes) and isn't actually available when time comes to generate the SignerInfo (only the details relevant to the SID are required).

I'm closing this one off for now, but we'll discuss it internally and see if we can come up with something. It may be the best approach is to introduce an extra sign/verify step into the JCA generators to validate the keys in place, possibly triggered by a setting so that people who don't wish to do the extra check can avoid the costs. Something to think about.
