### ISSUE TITLE
Will Bouncy Castle support every NIST Round 2 PQC Candidates?

### ISSUE THREAD

**Issue by dawud-tan** [bcgit/bc-java#522]
Will Bouncy Castle support every NIST Round 2 PQC Candidates, or just the winner?

**Comment by bcgit** [comment]
Hi,

Not sure. We’ll definitely include  the winners, we may support one or more of the other finalists depending on how the analysis stands up, and by that if an algorithm didn’t make the final cut and it was not eliminated due to some inherent weakness it would be a candidate for us to include.

Regards,

David

**Comment by dawud-tan** [comment]
I'm just wonder about how plaintiff or his attorney present digital contract and the digital signature to judge, do you know any real world case in civil law country? I mean how it was done in the past with pre-quantum digital signature, have any judge in the world face contract dispute that involve only digital contract and digital signature without a paper?

Thanks

**Comment by bcgit** [comment]
No idea on that one. Sorry. 

In other news our implementation of QTesla has been upgraded to round 2 and is now on https://www.bouncycastle.org/betas

**Comment by dghgit** [comment]
Okay, so the answer for round 2 is now, but for round 3 is yes. Note, due to what happened with SIKE it will not be supported beyond BC 1.72. 1.72 will have all the round 3 submissions/finalists except for Rainbow and GeMSS (these will both appear in 1.73).
