### ISSUE TITLE
Duplicate class warning (module-info) in bcprov and bcpkix introduced in 1.62

### ISSUE THREAD

**Issue by isaki** [bcgit/bc-java#537]
Version 1.62 introduced a duplicate class warning in bcprov and bcpkix with respect to their module-info entry when building a shaded JAR with maven.

```
[WARNING] bcprov-jdk15on-1.62.jar, bcpkix-jdk15on-1.62.jar define 1 overlapping classes: 
[WARNING]   - META-INF.versions.9.module-info
```

This warning is not present when shading a build that utilizes 1.61.

**Comment by bcgit** [comment]
The shaded code doesn't appear to be able to cope with multi-release jars. In this case it's probably safe to ignore the warning, but you might want to make sure the module-info class is not propagated, or if one is actually required that you build your own one from the source so that it properly captures what is in the jar.

**Comment by isaki** [comment]
Thankfully it is not required nor propagated for the project that generated this warning. I just wanted to bring this to your attention. Thank you for the info!
