### ISSUE TITLE
Question about Cobertura

### ISSUE THREAD

**Issue by Hartland-3** [bcgit/bc-java#544]
I am using the java release library for BC to use openPGP on a work project. However we must approve all open source libraries using a software called Snyk. The only security violation comes from the inclusion of Cobertura. I wanted to ask what its being used for and Is this package included in your release builds on the website?
https://www.bouncycastle.org/latest_releases.html

**Comment by kimmerin** [comment]
I'm not BouncyCastle but have used Cobertura myself. Cobertura is used together with JUnit to execute test cases and measure coverage so you know at the end of a test run, if test failed and what part of your source is covered by your tests.

Having 100% success rate with your tests doesn't mean much if you only covered e.g. 10% of your source so a combination of this you can see quite often "out there".

You can find more information about Cobertura Here[TM] around the corner at https://cobertura.github.io/cobertura/. Personally I switched to Jacoco due to very slow performance BTW.

It's only used during developement/production it's generally not part of a release.

**Comment by bcgit** [comment]
You can remove the references to cobertura in the build file quite safely. It is not included in any of the release builds for the Bouncy Castle project. As @kimmerin  points out, we just use it for checking code coverage.
