### ISSUE TITLE
Bad record mac alert received during dtls1.2 Handshake when using PSKTlsClient

### ISSUE THREAD

**Issue by roshanrajaratnam** [bcgit/bc-java#600]
Hi, I'm currently facing an issue when using PSKTlsClient with DTLSv1.2 where I keep receiving a Bad record mac alert (This happens when sending the client key exchange message), however this causes bouncy castle to retransmit the client key exchange. I don't receive the same alert after the retransmission. But the handshake does not continue after the retransmission either. The cipher suite that is being used is TLS_PSK_WITH_AES_128_CCM_8

**Comment by peterdettman** [comment]
I think there must be some confusion about the sequence of events. `bad_record_mac` should only come up at the end of the handshake, usually the `finished` message since it's the first protected record.

For a PSK client, the simplest cause of bad_record_mac will be that you have supplied the wrong PSK (pre-shared key) - or the wrong/mismatching identity, so I'd suggest double-checking that.

**Comment by roshanrajaratnam** [comment]
@peterdettman Thanks for looking into this. During the client key exchange there is a `finished` message that is being sent as the last dtls record of three where the first one is the `client key exchange record`, and the second being the `change cipher spec`. So like you are mentioning there is a finished message included in this exchange hence the bad record mac?

I will also look in to the wrong/mismatching identity tomorrow again.

**Comment by roshanrajaratnam** [comment]
@peterdettman Well what more can I say, you had it correct all the way. the PSK and the Identity was setup wrong in the server. Thanks for you tip.
