### ISSUE TITLE
Initializing TrustManagerFactory with empty keystore throws exception when using BSJSSE

### ISSUE THREAD

**Issue by jkakavas** [bcgit/bc-java#604]
Hi there folk, 

When using BCJSSE , attempting to call `init()` on `TrustManagerFactory` with an empty keystore causes an `InvalidAlgorithmParameterException` to be thrown. When using SunJSSE, the same call initializes a single TrustManager with no accepted issuers as expected. 

minimum reproduction 

``` java
import javax.net.ssl.TrustManagerFactory;
import java.security.KeyStore;

public class TestBCJSSE {

    public static void main(String[] args) throws Exception{
        KeyStore keyStore = KeyStore.getInstance(KeyStore.getDefaultType());
        keyStore.load(null, null);

        TrustManagerFactory sunTrustManagerFactory = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm(), "SunJSSE");
        sunTrustManagerFactory.init(keyStore);
        //no exception thrown
        TrustManagerFactory bcTrustManagerFactory = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm(), "BCJSSE");
        bcTrustManagerFactory.init(keyStore);
        //java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
    }
}
```

**Comment by peterdettman** [comment]
I've been thinking we might try and tolerate an empty trust store. Note that the SunJSSE case is not so straight-forward. From my notes:

"SunJSSE TrustManager with no trusted certs (empty trust store) lazily throws at checktime, breaking contract that check methods should throw CertificateException"

SunJSSE is only delaying the same InvalidAlgorithmParameterException since it lazily initialises the PKIX parameters internally (It's the PKIX parameters that don't like empty trust anchors, for both providers). It means that SunJSSE TrustManager calls fail with some RuntimeException instead of the documented CertificateException, which can easily escape notice and cause subtle errors.

So I actually feel BCJSSE has the better behaviour of the two at present, and it's just a question of whether there's any good reason for the restriction at all.

**Comment by djelinski** [comment]
I just run into this while trying to convert an application using Jetty from Java default providers to BCJSSE; when not instructed otherwise, Jetty's SSLContextFactory is using keystorePath to create trust store; since my keystore contains only key entries, and key entries are ignored during creation of trust manager, trust manager initialization fails.

I guess this is my +1 to not throwing during initialization.

**Comment by peterdettman** [comment]
We've adapted our TrustManager implementation to tolerate an empty trusted-certs set. i.e. it will no longer give the exception at initialisation time, and it will fail any actual check calls properly with a CertificateException.
