### ISSUE TITLE
Unreleased Resource: Streams 

### ISSUE THREAD

**Issue by Sathishdisys** [bcgit/bc-java#634]
### Issue Description 
The program can potentially fail to release a system resource.
Resource leaks have at least two common causes:
- Error conditions and other exceptional circumstances.
- Confusion over which part of the program is responsible for releasing the resource.
Most unreleased resource issues result in general software reliability problems, but if an attacker can intentionally trigger a resource leak, the attacker may be able to launch a denial of service attack by depleting the resource pool.

### Issue detected files
/libs​/sc-light-jdk15on-1​.47​.0​.2​.jar​ /org​/spongycastle​/asn1​ /BEROctetStringParser​.java
/libs​/sc-light-jdk15on-1​.47​.0​.2​.jar​ /org​/spongycastle​/asn1​/util​ /Dump​.java:17
/libs​/sc-light-jdk15on-1​.47​.0​.2​.jar​ /org​/spongycastle​/crypto​ /examples​/DESExample​.java:222
/libs​/sc-light-jdk15on-1​.47​.0​.2​.jar​ /org​/spongycastle​/crypto​ /examples​/DESExample​.java:203

**Comment by cesarhernandezgt** [comment]
Hi @Sathishdisys 

Does this apply to the latest 1.68 versions?

From the list of files, two of them are example code (DESExample​.java and DESExample​.java:), one a command line util class (Dump.java) and `/org​/spongycastle​/asn1​ /BEROctetStringParser​.java` seems to be the only one used by the API.

**Comment by Sachpat** [comment]
Hi @cesarhernandezgt @Sathishdisys , so is this a new vulnerability BC? The WhiteSource reports this against the library in our scans. Do we have a fix for this? Or are we planning to fix for this soon?. If needed, I would be happy to contribute also to this fix maybe with some of your assistance. :) .

**Comment by Sachpat** [comment]
I just had a look at the code base and the only considered class /libs​/sc-light-jdk15on-1​.47​.0​.2​.jar​ /org​/spongycastle​/asn1​ /BEROctetStringParser​.java though it doesn't close the stream handled by the parser, this input stream is provided by a caller. If the stream is provided by the caller, I am not sure why the parser must close it. I would let the caller do it because the caller created the stream. Also, the parser can create a stream but it is a byte arrays stream
https://github.com/bcgit/bc-java/blob/bc3b92f1f0e78b82e2584c5fb4b226a13e7f8b3b/core/src/main/java/org/bouncycastle/asn1/ASN1StreamParser.java#L35
There is no leak in this case. Hence I feel there is no vulnerability here.

**Comment by marceloDanubioZalayeta** [comment]
> Hi @Sathishdisys
> 
> Does this apply to the latest 1.68 versions?
> 
> From the list of files, two of them are example code (DESExample​.java and DESExample​.java:), one a command line util class (Dump.java) and `/org​/spongycastle​/asn1​ /BEROctetStringParser​.java` seems to be the only one used by the API.

Good day, 

Sonatype scan is returning the following for 1.69 version, is this a false positive?

Explanation
Bouncy Castle is vulnerable to Denial of Service (DoS). The Dump.class file utilises FileInputStreams objects when reading from user-provided files, but fails to close these streams properly. This can lead to resource leaks, potentially enabling an attacker to exhaust resources by providing a crafted file as an input to the application, thereby triggering a DoS condition.

Root Cause
bcprov-jdk15to18-1.69.jarorg/bouncycastle/asn1/util/Dump.class[1.46, )

**Comment by dghgit** [comment]
They're both false positives. 
BEROctetStringParser cannot close the underlying input stream as other parsers may need to be invoked on the same stream.

I've added a close to Dump. It's actually a command line utility though, not part of the API proper, the addition of the close should stop the complaints.
