### ISSUE TITLE
PATH authentication using XMSS/MT

### ISSUE THREAD

**Issue by akagaminosana** [bcgit/bc-java#659]
Hi bc community.

Well, thanks first for sharing such power-full library. 

I'm using actually bc for XMSS-MT signature scheme. signing and verifying works fine, but based on the Standard of XMSS published [https://tools.ietf.org/html/rfc8391](https://tools.ietf.org/html/rfc8391 ), a validity of a signature is based not only on the WOTS+ signature and the corresponding WOTS+ key, but the path from the signing leaf to the root.

by looking at XMSSMTSigner class, the verification algorithm does only PATH authentication, by comparing what he got from the constructed path (from the signing leaf) to the root. but there is no call for method (verifySignature from WOTSPLUS class) to validate the WOTS signature first. 

can someone please explain the provided verifying solution and if it convers both WOTSPLUS Signature verification and Path authentication? 

Best regards.

**Comment by bcgit** [comment]
It's true that verifySignature() isn't called in the API, but it does it's work using getPublicKeyFromSignature(). This is called from getRootNodeFromSignature() which is used by the verifySignature() methods for both XMSSMTSigner and XMSSSigner. getRootNodeFromSignature() requires the message to match in order to produce the correct return value (or put another way, the next steps will only work if the signature would have verified).

I have been unable to contact the original contributor of the code, but my feeling is that the verifySignature() method is left over code from testing. Comparing the Section 4.2.5. of the RFC with the actual code shows that the approach taken has produced Java code which lines up (approximately) with the pseudo-code provided in the RFC. It does look like the unused method can now be safely removed though, so we may do so in order to avoid any further confusion.

Does that answer your question?

**Comment by akagaminosana** [comment]
Hi

After looking at the Signing and verifying method from BC, it seems that the verifying process does everything: WOTSPLUS Signature verification and Path authentication. 

Thanks for the answer.
