### ISSUE TITLE
Client side SNI extension when using BCJSSE

### ISSUE THREAD

**Issue by gstanchev** [bcgit/bc-java#660]
BCJSSE doesn't add client side SNI in ClientHello. Some public servers reject such requests with alert 40. We used a Cloudflare-hosted service that rejected Java client (HttpsURLConnection) originated connection. We have configured BCJSSE as default JSSE provider. I read the BCTLS guide and used the workaround from section 3.2.5 to inject SNI which resolved the issue, however we are in control of this particular code, there are other places where similar calls are initiated from 3rd party libraries that are not under our control.

I was wondering why BCJSSE doesn't add SNI automatically. The guide states:

> Endpoint identification was introduced in 1.0.7 in a manner that tried to be as compatible with
SunJSSE as possible. Unfortunately, when using HttpsURLConnection SunJSSE uses some magic 
(reflection and/or internal API) to tell the socket about the "original hostname" used for the
connection, and we cannot use that same magic as it is internal to the JVM.

I do see in ProvSSLSocketDirect.notifyConnected() a call:
InetAddress peerAddress = getInetAddress();
...
this.peerHost = peerAddress.getHostName();

Can BCTLS use peerHost that is already resolved to add SNI when sending ClientHello?

**Comment by peterdettman** [comment]
The short answer is that HttpsURLConnection is not written to work correctly with JSSE providers apart from SunJSSE. You will struggle with 3rd party libraries that use it unless they provide sufficient hooks - in this case, to configure the SSL sockets and/or factories.

BCJSSE does add client side SNI to ClientHello, but only when the original hostname is available. Unfortunately when using HttpsURLConnection, it is not available to non-SunJSSE providers.

Three ways an SNI hostname can get inferred by an SSLSocket:

1. An SSLSocketFactory method including the hostname is used to create the socket.
2. setHost(String) is called on SSLSocketImpl (note this method is not in the public API).
3. getInetAddress() returns an InetAddress with the "originalHostname" (if any). 

BCJSSE supports (1) and (2).

Other HTTPS implementations tend to use (1), so things work fine, but HttpsURLConnection does not. Instead it uses (2) - restricted to instances of sun.security.ssl.SSLSocketImpl - and (3) - which is only accessible to JDK-internal code.

Also, without access to the originalHostName, it's also impossible to even know whether there _was_ one (or just an IP address). peerAddress.getHostName *might* contain it, or it might be a resolved name. We can't auto-add it for SNI if it's (possibly) resolved, because multiple hosts can share an IP address. (Also, SunJSSE doesn't add it in that scenario anyway, so compatibility).

I realise it's very frustrating, especially when you can literally see the correct hostname sitting there in the debugger (in your use case). Unfortunately BCJSSE has to work in the general case and it is not generally correct to treat that as an SNI hostname automatically.

**Comment by gstanchev** [comment]
Thank you for your explanation. I guess that ticket can be closed.
