### ISSUE TITLE
ECFieldElement Use Random - Is It Safe?

### ISSUE THREAD

**Issue by derekyuwork** [bcgit/bc-java#716]
I have an application using bcprov-jdk15on-1.65.jar. From an app scanning report, it says that my application uses an insecure random number generator. I checked and found that it is due to ECFieldElement using Random class instead of SecureRandom class. 

I would like to ask if this is safe to use Random here?

**Comment by bcgit** [comment]
Please write back to the application scanner and ask them to recognize when Random is being used in a numerical solver and not in security sensitive code so that they can stop flagging false issues. 

Many algorithms, particularly those using polynomials require the use of various types of root solvers, while these could be modified to use SecureRandom the performance hit would be significant with no gain in security (actually it may have a negative effect as it would encourage the use of smaller keys...). SecureRandom does matter for things like key generation and validation, it does for functions which are just performing numerical methods that have security implications.

**Comment by derekyuwork** [comment]
Understood. Thanks a lot bro.
