### ISSUE TITLE
CVE-2020-0187

### ISSUE THREAD

**Issue by otaconix** [bcgit/bc-java#767]
As I couldn't find an issue that tells me this is being worked on, I thought it'd be nice to have an issue here so we can track progress.

> In engineSetMode of BaseBlockCipher.java, there is a possible incorrect cryptographic algorithm chosen due to an incomplete comparison. This could lead to local information disclosure with no additional execution privileges needed. User interaction is not needed for exploitation.

https://nvd.nist.gov/vuln/detail/CVE-2020-0187

> In Conscrypt, we're adding AES/GCM-SIV/NoPadding as a cipher, which is
a different cipher than AES/GCM/NoPadding.  Bouncy Castle previously
treated any mode that started with "GCM" as being GCM, which now means
it will supply the (incorrectly functioning) GCM mode when GCM-SIV is
requested.  Make the match more strict to keep that from happening.

https://android.googlesource.com/platform/external/bouncycastle/+/14ceec126e49f2f4748f0d540be820515cc725a6

**Comment by cesarhernandezgt** [comment]
Hi @otaconix, does Bouncy Castle currently support GCM-SIV cipher?
Base on my understanding of the [link](https://android.googlesource.com/platform/external/bouncycastle/+/14ceec126e49f2f4748f0d540be820515cc725a6) you shared, it seems this CVE becomes relevant by the usage of such cipher. 
https://android.googlesource.com/platform/external/bouncycastle/+/14ceec126e49f2f4748f0d540be820515cc725a6%5E%21/#F0

**Comment by dghgit** [comment]
We don't, so I can understand why this was an issue on the Android platform and they didn't inform us of it - it's obvious that the issue was just considered in the light of "GCM confusion" as several other modes would exhibit the same problem and they don't appear to have changed the code for those. 

That said I don't any of us would call this behavior a feature, while you would expect it to be immediately obvious something was working in heterogeneous environment it would be better for everyone if a NoAlgorithmException was generated instead of expecting someone to tear out the required amount of hair to work out what the issue really was. I've pushed an update for BaseBlockCipher which should take care of this.

**Comment by otaconix** [comment]
Hey @dghgit, your changes are looking good. Was the change in `CFBBlockCipher` intentional? If so, there seems to be no corresponding test.

Anyway, I'm afraid I'm not going to be able to judge whether anything else should be done about this issue, as I'm not a direct user of Bouncy Castle. I created this issue mostly to hear from the maintainers whether this issue could affect the official releases, and if it did, to have it fixed.
So feel free to close the issue if you think you've done enough.

**Comment by dghgit** [comment]
Yes, the change was intentional, the new bounds check is triggered via BlockCipherTest. 

Thanks for the report, I'll mark this one as closed.

**Comment by mouse07410** [comment]
This one is closed. Would you mind sharing your plans regarding support of AES-GCM-SIV, please?

My user car requires it's properties, and it works be nice if Java client could exchange messages with the SIV-capable backend.

Thanks!

**Comment by otaconix** [comment]
The vulnerability scanner my employer uses has seen @dghgit's commits and (probably correctly) concluded the issue wasn't just with GCM-* modes, which makes it flag it with a new vulnerability.
Can we expect a release containing these changes soon?

**Comment by dghgit** [comment]
The CVE is on Android 10.

**Comment by dghgit** [comment]
I've decided my original answer was possibly a bit harsh and I now think I know where the confusion is here.

The reason the CVE is raised on Android is while it does apply to Android, the issue is as much about what Android provides, not what the implementation of BC does. There is nothing to prevent a JCE provider returning the same cipher that the other provider on Android returns as "AES-GCM-SIV" as "GCM". There isn't really a standard in force for JCE algorithm names, at best there is common agreement, and this has been the documented behavior of the APIs since they first came out - as a result we have people who return AES/CBC/PKCS7Padding for "AES" and others like us who return "AES/ECB/NoPadding", or "RSA" as "RSA/NONE/NoPadding" and also "RSA/NONE/PKCS1Padding". The "vulnerability" here is that on the Android platform they want to be sure that "AES-GCM-SIV" will only match their definition even if someone fails to specify the provider. The fix I have provided is to reduce the likelihood of confusion as BC now enforces tighter checks around several modes, but I have simply done it more generally. It needs to be understood though, for the reasons I have already given I have not eliminated the possibility of someone using the general JCE mechanism without specifying a provider and getting back an algorithm other than the one they expect. I have just made it less likely, in the same way as the Android team has for the issue they faced, expect I have made it even less likely then they did (probably).

Please ask whoever wrote the vulnerability scanner to brush up on how the JCE API is actually documented as working and what guarantees it actually makes. I am happy to discuss this with them further if it is not understood what I am trying to say.
