### ISSUE TITLE
Quick question concerning some Cipher algorithms

### ISSUE THREAD

**Issue by veli4ko91** [bcgit/bc-java#776]
Hey! :)
Sorry if I am not asking my question in the correct section. I am using BouncyCastle, specifically in the following call:

` final ContentSigner signer = new JcaContentSignerBuilder(algorithm).setProvider(provider).build(privatekey);
// here I suppose we could put only Signature algorithms, right?`

I also have a bit of a more generic question about the following call:

`final KeyPairGenerator generator = KeyPairGenerator.getInstance(algorithm, provider); 
// while this is not BouncyCastle, it uses only KeyPairGenerator algorithms?`

My question is related to a certain fix that was made recently in https://github.com/bcgit/bc-java/commit/b462106a57b7f5079bea0ac95ca12105755d2c0f . Since I am using KeyPairGenerator and Signature algorithms from here:
https://docs.oracle.com/javase/7/docs/technotes/guides/security/StandardNames.html#Signature  , should I worry about the Cipher algorithms that have been patched? I am using BouncyCastle 1.60 .

Sorry for the rookie question. Not very experienced with security :)

**Comment by martijnbrinkers** [comment]
If you look at the source of JcaContentSignerBuilder, you will see that the supported algorithms are listed in org.bouncycastle.operator.DefaultSignatureAlgorithmIdentifierFinder. The list of supported ciphers is a long list. 

The commit b462106a57b7f5079bea0ac95ca12105755d2c0f seem make mode name checking more strict, for example case sensitive check instead of case insensitive etc. Not sure whether this is a security related fix. It also looks like this is only relevant for older JDK version (1.3 and 1.4)

**Comment by veli4ko91** [comment]
Okay, thanks for the fast response :)
It seems that the algorithms which were patched in https://github.com/bcgit/bc-java/commit/b462106a57b7f5079bea0ac95ca12105755d2c0f are not the same as the ones listed in the DefaultSignatureAlgorithmIdentifierFinder. Does that mean there are a different subset of algorithms,and thus my call is safe when using the non-patched version?

**Comment by dghgit** [comment]
Yes.
