### ISSUE TITLE
Google Play Blocker: Unsafe SSL TrustManager Defined

### ISSUE THREAD

**Issue by joelhyman** [bcgit/bc-java#803]
Hi, I am using bouncycastle as apart of another library (Certificate Transparency [https://github.com/babylonhealth/certificate-transparency-android](url) ) in an Android app. The app was scanned for security vulnerabilities and identified the following in this file:

[https://github.com/bcgit/bc-java/blob/bc3b92f1f0e78b82e2584c5fb4b226a13e7f8b3b/pkix/src/main/java/org/bouncycastle/est/jcajce/JcaJceUtils.java#L48](url)

The affected classes define an empty checkServerTrusted() method, thereby disabling SSL validation and hence accepting any SSL certificate as valid, if the class is used when connecting to a server over SSL/TLS.

Regardless of whether the affected classes are actually used at runtime or not, Google Play is blocking any App that defines such an insecure X509TrustManager, as detailed on Google's support page:

"Beginning May 17, 2016, Google Play will block publishing of any new apps or updates containing the unsafe implementation of the interface X509TrustManager."

Can bouncycastle be updated to use the recommended code, please?

**It recommends a more secure code in this nature:**
`// Retrieve the system's default trust manager
    private static final X509TrustManager defaultTrustManager = getSystemTrustManager();
    private static X509TrustManager getSystemTrustManager() {
        X509TrustManager systemTrustManager = null;
        TrustManagerFactory trustManagerFactory;
        try {
            trustManagerFactory = TrustManagerFactory.getInstance(
                    TrustManagerFactory.getDefaultAlgorithm()
            );
        } catch (NoSuchAlgorithmException e) {
            throw new IllegalStateException("Should never happen");
        }
        try {
            trustManagerFactory.init((KeyStore)null);
        } catch (KeyStoreException e) {
            throw new IllegalStateException("Should never happen");
        }

        for (TrustManager trustManager : trustManagerFactory.getTrustManagers()) {
            if (trustManager instanceof X509TrustManager) {
                systemTrustManager = (X509TrustManager)trustManager;
            }
        }

        if (systemTrustManager == null) {
            throw new IllegalStateException("Should never happen");
        }
        return systemTrustManager;
    }

    // This is the method responsible for validating the server's certificate
    @Override
    public void checkServerTrusted(X509Certificate[] x509CertificateArray,
                                   String authType) throws CertificateException {

        // Use the system's trust manager to do baseline SSL validation
        defaultTrustManager.checkServerTrusted(x509CertificateArray, authType);
        // If the default validation succeeded, add additional checks on the certificate here
    }`

**Comment by BlackthornYugen** [comment]
For some reason your link didn't work for me. But I am pretty sure you are refering [to this](https://github.com/bcgit/bc-java/blob/r1v60/pkix/src/main/java/org/bouncycastle/est/jcajce/JcaJceUtils.java#L48). It looks like this trust manager was explicitly written to trust everything (hopefully people that do need this use it responsibly because Google is correct, it is dangerious and probably isn't a good idea on android or anywhere outside testing but maybe there is a good use case...

But since the trust manger is given out by calling `getTrustAllTrustManager`, hopefully it's used responsibly. If your not activly using this trust manager. Would it be possible to configure ProGuard to exclude it from your apk? 

Removing it from bouncy castle would likley be a [breaking change for a few people](https://github.com/search?q=getTrustAllTrustManager&type=code).

**Comment by joelhyman** [comment]
Hi thanks alot for answering. Just seeing the reply. I have ended up cloning the repo and making my own modifications. I will close this issue.
