### ISSUE TITLE
CVE-2005-0366 mismatch?

### ISSUE THREAD

**Issue by gamma** [bcgit/bc-java#849]
Hi there, for some days now the OWASP dependency check is reporting v1.67 to be vulnerable to CVE-2005-0366.

I wonder if this is a mismatch on OWASP side or if BC is indeed vulnerable? I have not found a reference to the CVE in the codebase or issue tracker.

**Comment by dghgit** [comment]
I assume you're talking about 1.67. I had some trouble finding the details on this one, fortunately there is a good write up here:

https://lists.gnupg.org/pipermail/gnupg-announce/2005q1/000191.html

As far as I can tell BC is not vulnerable, BC has never supported a quick scan feature. If you're using an integrity packet you'll get to verify it the hard way - the whole message has to be decrypted and then you'll need to explicitly do the verification and the digest is checked in constant time. If someone believes otherwise I would be happy to talk to them.

**Comment by gamma** [comment]
yeah, you're right about the version, sorry for the mixup. Question is: why does OWASP believe, that BC is effected.

**Comment by gamma** [comment]
It is OK if you do not want to check on this issue any further - the OWASP pattern match is a lo confidence match with erroneous information; We did just update to 1.67 which did not match our exclusion patterns anymore.

I'll close this for now - if you think this should be investigated further, please re-open.
