### ISSUE TITLE
security vulnerability: hash collision

### ISSUE THREAD

**Issue by avodonosov** [bcgit/bc-java#850]
https://sca.analysiscenter.veracode.com/vulnerability-database/security/sca/vulnerability/sid-27749/summary

**Comment by dghgit** [comment]
We have contacted Veracode about this. I believe they are in the process of correcting the report. It is not correct.

**Comment by avodonosov** [comment]
Thank you for looking into this

**Comment by dghgit** [comment]
This is an updated response as MITRE have now fixed the wording of the CVE to reflect what it is actually about, which is BKS, not BKS-V1 (BKS-V1 did not exist as a keystore type prior to 1.49) Please see https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-5382 for further details

We are hoping the new wording will clear this up for the tool vendors.

**Comment by avodonosov** [comment]
@dghgit, so is this vulnerability present in the last version?

**Comment by avodonosov** [comment]
The Veracode report now says a vulnerability exists, but the vulnerability has no CVE assigned. And their report is specifically about BKS-V1:

> Bouncy Castle is vulnerable to hash collision attacks. The library keystore files uses a HMAC hash that is only 16 bits long, allowing a malicious user to retrieve the password used for keystore integrity verification checks. This vulnerability only affects users of the `BKS-V1` keystore format, which was re-introduced since 1.49. Since it is re-introduced in Bouncy Castle 1.49, users of Bouncy Castle 1.49 and above may be affected if the legacy BKS-V1 is being used. To remediate the vulnerability, ensure that there are no usage of BKS-V1.

@dghgit,since BKS-V1 is a new format only introduced for users who want to interoperate with legacy versions, it would, probably, be good to have this keystore type support provided by a separate artifact (for example, bcprov-legacy-support-jdk15on), so that the bcprov-dk15on by itself does not raise any questions.

**Comment by dghgit** [comment]
I think I draw the line at creating yet another separate set of jars for this one. BKS-V1 is documented as having a 16 bit checksum, BKS appeared to have a 160 bit prior to 1.47. There's a fundamental difference between a keystore that claims to do something and doesn't and one that just claims to do something limited. The only thing I am particularly sure of is there are still people needing to produce these files. I think the only additional option we have is to add a system property to enable BKS-V1 and have it disabled by default.

**Comment by avodonosov** [comment]
@dghgit ,I agree that the current separation is more clear.

I was not proposing a set of jars. just a single jar that contains the BKS-V1support. 

As for the system property, it does not change anything, no need to introduce it, IMHO. Because today one needs explicit Java code to invoke the BKS-V1 functionality (as I understand), and so it is not enabled by default. If so, there is no difference between adding explicit Java code and explicitly setting a system property.

Speaking of Veracode 3rd party libraries analisys, it reports issues by mere presence of a library in the application, even if the application does not call the vulnerable functionality. Controlling the availability of the functionality by a system property will not prevent the issue from being reported, I believe.

**Comment by dghgit** [comment]
I was hoping  part of the issue was related to worries that a third party jar might include use of the functionality. A system property will at least stop that happening by accident - in the same way as leaving a special purpose jar out of the class path would.

Looking back at the opening statement in the report "Bouncy Castle is vulnerable to hash collision attacks." - apart from the fact the statement is so broad as to be untrue, from emails we receive it doesn't appear users get any further in understanding what is being said. The current reporting is causing huge amounts of distress to our users, wasting large amounts of our time (which is already in very short supply) explaining what it means, and putting us in the position where we have to tell people to ignore what the tool is reporting (which we do not like either). I will just have to hope for the best.

**Comment by avodonosov** [comment]
@dghgit, well, a 3rd party lib can also call `System.setProperty(...)`...

**Comment by dghgit** [comment]
It's a very good point. We moved to a model a while ago where BC properties can also be set in java.security - where this is done the property setting will override any attempts to set it locally, even is a thread override, will be ignored.

I still wonder that the wrong tool is being used for the job here, as you say, Veracode is generating the warning even if the application is not using BKS-V1, which at this point it only would be if it actually needed to, and it's really a warning that needs to be made by a source code analyser. Instead we're seeing a warning being flagged which is generally not necessary and we are having to deal with the distress and confusion it is causing as a result because the way it is being delivered is making people think it is an inherent issue in the library.

**Comment by dghgit** [comment]
Okay, for anyone who is interested 169b05 which has the security property present is now available at https://www.bouncycastle.org/betas If anyone can get Veracode (at least) to evaluate it and determine that it meets whatever it is that they are trying to do I would be grateful.

**Comment by avodonosov** [comment]
@dghgit , thank you for working on this.

I don't know if there are ways for Veracode to "evaluate" solutions, I suspect they simply track publicly reported vulnerabilities for libraries, and as soon as the lib is present in classpath, raise an issue for an application.

I am trying to understand the solutions myself. (For others interested:
https://github.com/bcgit/bc-java/commit/bae3939b9c7996163dcabb23dc9d80b2d188b580
https://github.com/bcgit/bc-java/commit/f24ebb55dc07b2b1120ae601e82ce990fa75c8e1)

**Comment by avodonosov** [comment]
@dghgit 

> I still wonder that the wrong tool is being used for the job here, as you say, Veracode is generating the warning even if the application is not using BKS-V1, which at this point it only would be if it actually needed to, and it's really a warning that needs to be made by a source code analyser. 

Security scanners produce lot of noise, that's natural. In most cases their issues are "warnings" - a call for attention, not a 100% guaranteed bug.

> and we are having to deal with the distress and confusion it is causing as a result because the way the warning is being delivered is making people think it is an inherent issue in the library.

Note, the developers who have to deal with such issues, are often don't know what it is about. Even if that the developer who authrored the corresponding part of the application code. (But when an issue is signaled about a library (e.g. bc-prov-jdk-15-on) that application uses, it's difficult to know what developer owns the related app functionality, especially if the app does not use this functionality at all).

BTW, when opening this github issue I had no idea what hashcode it is, what even what bc-proj-jdk15on does. Only after the discussion I started to understand the hashcode probably controls a keystore file integrity.

It's good when a company has a security department which can approve not doing what Veracode requires, after analyzing the issue. Sometimes the poor develper is demanded to do exactly what security scanner says.

**Comment by avodonosov** [comment]
@dghgit , after reading the fix, and the code of the ` Properties.isOverrideSet` here https://github.com/bcgit/bc-java/blob/bc3b92f1f0e78b82e2584c5fb4b226a13e7f8b3b/core/src/main/java/org/bouncycastle/util/Properties.java, to me it like that unless we explicitly set java security property `org.bouncycastle.bks.enable_v1=false` any 3rd party library can enable BKS-V1 by simply calling `Security.setProperty('org.bouncycastle.bks.enable_v1", "true")` or `System.setProperty('org.bouncycastle.bks.enable_v1", "true")', right?

**Comment by dghgit** [comment]
Yes, although if a third party library is doing that, they'd probably want to document it in order to make sure it was not disabled as they'd probably have a reason (most likely connected with Android). Keep in mind the file format is public, the source for the KeyStore is available and providers that only implement KeyStore's do not need to be signed. There is nothing to prevent a third party library from processing these files even if we remove the implementation completely from the provider.

**Comment by dghgit** [comment]
One other thing, we have heard back from Veracode - the addition of the property meets their requirements to stop reporting the issue. I gather because it forces people to express intent.

**Comment by sguillope** [comment]
I can confirm that the latest Veracode scan results we received recommended to upgrade to BC 1.69 (which obviously doesn't exist yet) to resolve the vulnerability. They are specifically pointing to commit 7b66244e14488c5c981415b02ff71837ff3d2d50 as being the vulnerability patch.
Cheers!
