### ISSUE TITLE
ECCurve uses equal(=) sign internally instead of the Equal function

### ISSUE THREAD

**Issue by emad7105** [bcgit/bc-java#858]
Hi guys,

I was wondering why the [`Equal`](https://github.com/bcgit/bc-java/blob/b9891bd460a7a938cf642444a0164d5e5c94fba2/core/src/main/java/org/bouncycastle/math/ec/ECCurve.java#L562) function in the [`math/ec/ECCurve.java`](math/ec/ECCurve.java) is never used in the `ECCurve.java` itself. 

I'm importing some (decoded) points and the curve object is somehow not the same object as in the `ECPoint`'s. However, the curve is the same curve and the `Equal` function evaluates to true. But [this line](https://github.com/bcgit/bc-java/blob/b9891bd460a7a938cf642444a0164d5e5c94fba2/core/src/main/java/org/bouncycastle/math/ec/ECCurve.java#L555) uses a plain equal sign instead, and of course, the Java objects are not the same. The other instance is [here](https://github.com/bcgit/bc-java/blob/b9891bd460a7a938cf642444a0164d5e5c94fba2/core/src/main/java/org/bouncycastle/math/ec/ECCurve.java#L530).

Is there any reason for that? Or it's some sort of a mistake?

Cheers!

**Comment by peterdettman** [comment]
It's not a mistake. ECCurve methods taking existing ECPoint instance(s) are intended to be used only on points actually created by the specific ECCurve instance. If you are unsure of the provenance of an ECPoint instance, you can use ECAlgorithms.importPoint to recreate it (if necessary) on the actual ECCurve you are using. However I would probably advise to work with byte encodings in your APIs to avoid this issue.

It's not really a common problem, so I am curious how you are getting points from different curve instances. If you can show some code, it may be that I would see some simpler problem with it.

**Comment by emad7105** [comment]
Hi Peter, thanks for your response and the suggestion.

I would like to share my code from our (prototype) project; however, the codebase is quite chaotic. So I grabbed the relevant nuggets in [a small repository](https://github.com/emad7105/bcectests/blob/main/src/main/java/Main.java) for you. The following line evaluates to true:  

```Assert.check(q.getCurve().equals(domainParams.getCurve()));```

Anyways, your suggestion to use `ECAlgorithms.importPoint` fixed my problem. It's commented in the code. When I uncomment it, it will be fine.

**Comment by peterdettman** [comment]
@emad7105 I took a quick look at your example. I suggest replacing this method:

```
    private static ECDomainParameters createECDomainParams(String curve) {
        X9ECParameters ecp = CustomNamedCurves.getByName(curve);
        if (ecp == null)
        {
            ecp = ECNamedCurveTable.getByName(curve);
        }

        ASN1ObjectIdentifier oid = ECNamedCurveTable.getOID(curve);
        return new ECNamedDomainParameters(oid, ecp);
    }
```

By using `ECNamedDomainParameters`, the encoded keys will identify their curve using a standard OID instead of explicitly specifying the curve parameters. Thus, when parsing, the OID is recognized and the global curve looked up instead of a new `ECCurve `instance being created.

`CustomNamedCurves` has optimized code for many popular curves (including this one) that is many times faster than the implementation you would get from `SECNamedCurves` (or this better fallback of `ECNamedCurveTable`).

You should still use `importPoint` since it will validate that the encoded point is actually for the expected curve.
