### ISSUE TITLE
bc-fips-1.0.2.jar with JDK 11.0.9 using TLSv1.3  throwing error: No available authentication scheme

### ISSUE THREAD

**Issue by Kish-Jadhav** [bcgit/bc-java#871]
Hi,

I have configured Apache Tomcat container resident server to use FIPS, using bc-fips-1.0.2.jar.

And while using TLSv1.3, I am getting below error, whereas, same configuration works with TLSv1.2
 javax.net.ssl.SSLHandshakeException -- javax.net.ssl.SSLHandshakeException: No available authentication scheme

The underlying java version is JDK11.0.9.

FYI. Without FIPS configuration, TLSv1.3 works properly.

Does bc-fips supports TLSv1.3?

**Comment by peterdettman** [comment]
May I ask why you are using the bc-fips jar instead of the regular (non-FIPS) provider jars? It is far from a simple drop-in replacement and will almost certainly not be worth the trouble unless you have a specific need for FIPS compliance.

To your issue: bc-fips jar is a cryptographic provider only and does not contain a TLS implementation. The error above is coming from SunJSSE and has something to do with not being able to find suitable credentials. Perhaps the only certificates available are using algorithms no longer supported in TLS 1.3, it's difficult to guess. If you want to understand the problem better I suggest you first try it without any BC jars, then perhaps using a non-FIPS BC provider (bcprov???.jar). You could also try using our non-FIPS bctls jar which has our own JSSE implementation ("BCJSSE").

We also provide a separate jar bctls-fips which contains our BCJSSE provider with modifications from the non-FIPS version, designed to be used in conjunction with bc-fips. Basic TLS 1.3 support was added in the most recent version (1.0.11). If you genuinely need FIPS then this is the recommended combination, but you will need to read the user guides and security policy accordingly. Support contracts for the FIPS libraries are available through Crypto Workshop (https://www.cryptoworkshop.com).

**Comment by Kish-Jadhav** [comment]
Thank you for response.

Yes there is need of FIPS compliance and hence using bc-fips.

Without bc-fips configuration (without any BC jars), same certificates and provided passwords are working well with TLSv1.3. 
When we use bc-fips with TLSv1.2, same setup (certs and passwords) works fine.

To become fips compliance are you suggesting to use BCJSSE implementation. Basically, the bc-fips-1.0.2.jar in conjunction with bctls-fips-1.0.11.jar? if yes, is bc-fips.jar not compatible with SunJSSE provider, as it used to be?

**Comment by peterdettman** [comment]
Yes we recommend you use bctls-fips jar since it actually is FIPS-aware (can/should be configured in FIPS mode per the user guide). SunJSSE used to have a FIPS mode, but we understand it was effectively disabled/removed since JDK 9 (see https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8217835).

We are happy to fix any issues in bc-fips that are causing problems when used with SunJSSE (e.g. typically SunJSSE starts depending on new classes or algorithms with new JDK versions), but updating that jar requires an expensive and time-consuming certification process, so it only happens perhaps once a year (no fixed schedule though).

In this specific case, it's still not clear whether the observed behaviour is a bug or a FIPS limitation. It will be easier to analyse in any case if you try bctls-fips with bc-fips, or even the bctls jar with bcprov (i.e. the regular bc-java setup) for comparison.

**Comment by dghgit** [comment]
Appears resolved so closing. Just to confirm though the BCJSSE, when configured for FIPS, is the only solution for Java 11 which will conform to SP 800-52.
