### ISSUE TITLE
BCJSSE TLS 1.3 server does not support EC TLS server certificates

### ISSUE THREAD

**Issue by martin-robo** [bcgit/bc-java#913]
Creating ticket after mail exchange that happend over dev-crypto at 05.03.2021. 
**BCJSSE TLS 1.3 server** does not support a key manager based on **EC** TLS server certificates.
Also I need to use **Brainpool** curves here. Mr. Peter Dettman mentioned this would be a little more difficult to integrate at this point.

**Comment by peterdettman** [comment]
TLS 1.3 support for ECDSA credentials is now implemented (including brainpool) and will be released in 1.69 in a few days.

Note that use of brainpool in TLS 1.3 requires enabling support for the SignatureScheme and NamedGroup types from [RFC 8734](https://datatracker.ietf.org/doc/html/rfc8734). We have included these in our default configuration but other implementations might not support them at all, or might not enable them by default.

Also, we currently have them unconditionally disabled if BCJSSE is used in FIPS mode.

Finally, not all cryptographic providers support brainpool curves in their ECDSA implementations (e.g. the SunEC provider apparently only got them in JDK 11). Therefore you may need to place the BC provider at highest priority in order to guarantee cryptographic support (BCJSSE checks for it and will disable the brainpool signature schemes if it's not present).
