### ISSUE TITLE
Mutual authentication fails during client verify with invalid algorithm exception

### ISSUE THREAD

**Issue by sumeetbadwal** [bcgit/bc-java#938]
BC jars versions:

bctls-fips-1.0.11.jar from bctls-fips-1.0.5.jar
bc-fips-debug-1.0.2.jar from bc-fips-1.0.1.jar
bcpkix-fips-1.0.5.jar from bcpkix-fips-1.0.1.jar

We are seeing the  following exceptions in our logs after upgrading BC jars.

 java.lang.IllegalStateException: Invalid algorithm: {sha256(4),ecdsa(3)}

 at org.bouncycastle.tls.crypto.impl.jcajce.JcaTlsRSASigner.generateRawSignature(Unknown Source)

 at org.bouncycastle.tls.DefaultTlsCredentialedSigner.generateRawSignature(Unknown Source)

 at org.bouncycastle.tls.TlsUtils.generateCertificateVerifyClient(Unknown Source)

 at org.bouncycastle.tls.TlsClientProtocol.handleHandshakeMessage(Unknown Source)

 

From the pcap analysis, the ssl handshake fails during client certificate verify stage.
From the BC code and the generated exception, It looks like the signature algorithm picked up by the client is ecdsa_.._sha256, but the signer being used is rsa signer.
Our client uses only rsa keys for client authentication with signature sha256WithRSAEncryption. 
The supported signature algorithms from the server are in the order below, In non fips case(and in older BC jars) rsa_pkcs1_sha256 is the desired signature algorithm by the client so handshake goes through successfully. ** 
    Signature Algorithm: ecdsa_secp256r1_sha256 (0x0403)
    Signature Algorithm: rsa_pkcs1_sha256 (0x0401)
    Signature Algorithm: ecdsa_secp384r1_sha384 (0x0503)
    Signature Algorithm: rsa_pkcs1_sha384 (0x0501)
    Signature Algorithm: ecdsa_secp521r1_sha512 (0x0603) 

We could find a work around for this problem by disabling EC support explicitly by setting org.bouncycastle.ec.disable=true . 
Can you let us know if this is a known issue,  or if there is a fix for this issue ?

**Comment by dghgit** [comment]
What cipher suites are enabled in the client? The server is unlikely to offer ECDSA if the client isn't offering it. Also what key and trust managers are the client using?

**Comment by peterdettman** [comment]
We've had a couple of similar reports previously (e.g. https://github.com/bcgit/bc-java/issues/916). In both cases it was caused by a failure to use the BCJSSE KeyManagerFactory (a BCJSSE SSLContext can only be used with its own KeyManagerFactory and TrustManagerFactory).

One option is to configure the default KMF type to PKIX in JAVA_HOME/conf/security/java.security:

ssl.KeyManagerFactory.algorithm=PKIX
ssl.TrustManagerFactory.algorithm=PKIX

If that doesn't fix things, do you have Java Logging enabled? It would show us some more details during the process of signature algorithm selection and KeyManager lookup.

e.g. edit your JAVA_HOME/conf/logging properties:

```
#java.util.logging.ConsoleHandler.level = INFO
java.util.logging.ConsoleHandler.level = FINEST
org.bouncycastle.jsse.level = FINEST
```

Please post the resulting logs.

**Comment by dghgit** [comment]
Assumed fixed as no further response.
