### ISSUE TITLE
Can we clearsign in non-ascii armored text

### ISSUE THREAD

**Issue by Susmit07** [bcgit/bc-java#951]
We do have a api called beginClearText() in ArmoredOutputStream, but for non-ascii armored text is it possible to apply clear text signature? 

Is it a known limitation to be addressed in future releases?

**Comment by Susmit07** [comment]
@dghgit @peterdettman can you please help

**Comment by dghgit** [comment]
I'm pretty sure this would never work, there's a couple of features with cleartext signatures such as dash escaping and canonicalisation which would wreak havoc with binary data. If you need to ship binary data like this I would suggest generating encapsulated signatures which contain the data, rather than detached signatures such as what you usually see with PGP MIME. You can still armor the result if it needs to be sent over email or something similar.
