### ISSUE TITLE
How to resolve this exception : org.bouncycastle.cms.CMSException

### ISSUE THREAD

**Issue by Amanvanawat** [bcgit/bc-java#978]
SemDecrypter::tryDecryptAsn1() - exception [org.bouncycastle.cms.CMSException: Unexpected object reading content.] ... Caused by: java.lang.ClassCastException: org.bouncycastle.asn1.DLApplicationSpecific cannot be cast to org.bouncycastle.asn1.ASN1SequenceParser

**Comment by peterdettman** [comment]
Please confirm the version of BC you are using and provide a full stack trace (ideally with line numbers). I think the CMS ...Parser classes can't handle APPLICATION tagged ASN.1 objects correctly at present.

We are working on improved handling of tagged objects during this release cycle, so this will work in due course. As a workaround (and to check that the data is correctly formatted) you could try using the simple non-Parser class (e.g. instead of CMSSignedDataParser, use CMSSignedData),  to load the data instead.

**Comment by dghgit** [comment]
To be honest, given it's a decrypt, if I saw this I would suspect I was using the wrong key and I'd decrypted the data to garbage.

**Comment by dghgit** [comment]
Closing as inactive.
